// Seed script to populate 90 additional formula entries (we already have 10)
// Run via: npx ts-node --compiler-options '{"module":"CommonJS"}' scripts/seed-100.ts

const API_URL = process.env.API_URL || 'https://project-aiub5.vercel.app';
const ADMIN_SECRET = process.env.ADMIN_SECRET || 'colorlab-admin-2026';

interface FormulaEntry {
  beforeHairColor: string;
  beforeHairType: string;
  beforeCondition: string;
  beforeLevel: string;
  afterHairColor: string;
  afterLevel: string;
  technique: string;
  formulaDetails: string;
  colorBrand: string;
  colorLine: string;
  colorShades?: string[];
  developer?: string;
  developerRatio?: string;
  lightener?: string;
  lightenerMix?: string;
  toner?: string;
  tonerDeveloper?: string;
  additives?: string[];
  processingTime: string;
  tags: string[];
  difficulty: string;
  priceRange: string;
  estimatedTime: string;
  notes: string;
}

const formulas: FormulaEntry[] = [
  // ─── BLONDE VARIATIONS (11-25) ───────────────────────────
  {
    beforeHairColor: "Level 6 dark blonde with warm gold undertones",
    beforeHairType: "1B straight, medium porosity",
    beforeCondition: "Virgin hair, healthy",
    beforeLevel: "6",
    afterHairColor: "Level 9 icy platinum blonde",
    afterLevel: "9",
    technique: "Full foil highlights with toner",
    formulaDetails: "Full head foils with fine weaves. Lightener: Wella Blondor + 30 vol (1:2). Process 45 min checking every 15. Must reach pale yellow level 10. Tone: Wella T18 Lightest Ash Blonde + T14 (1:1) with 10 vol. Process 20 min.",
    colorBrand: "Wella",
    colorLine: "Blondor / Color Charm",
    colorShades: ["T18", "T14"],
    developer: "30 vol lightener, 10 vol toner",
    developerRatio: "1:2",
    lightener: "Wella Blondor",
    toner: "T18 + T14 equal parts",
    tonerDeveloper: "10 vol",
    additives: ["Olaplex No.1"],
    processingTime: "45 min lightener, 20 min toner",
    tags: ["platinum", "icy-blonde", "full-foil", "wella", "cool-tone"],
    difficulty: "advanced",
    priceRange: "$$$$",
    estimatedTime: "4-5 hours",
    notes: "Multiple sessions may be needed if hair is resistant. Do not exceed level 10 lift in single session."
  },
  {
    beforeHairColor: "Level 5 medium brown with red undertones",
    beforeHairType: "2A wavy, medium porosity",
    beforeCondition: "Previously colored darker, 4 months ago",
    beforeLevel: "5",
    afterHairColor: "Level 7 warm honey blonde highlights",
    afterLevel: "7",
    technique: "Partial foil highlights",
    formulaDetails: "Partial foil - top section and face frame only. Redken Flash Lift + 20 vol (1:1.5). Weave medium sections. Process 35 min. Tone with Shades EQ 7GB + 7G (2:1) with processing solution. Process 15 min.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["7GB", "7G"],
    developer: "20 vol",
    developerRatio: "1:1.5",
    lightener: "Flash Lift",
    toner: "Shades EQ 7GB + 7G",
    additives: ["Olaplex No.1"],
    processingTime: "35 min lightener, 15 min toner",
    tags: ["honey-blonde", "partial-foil", "warm-tone", "highlights", "natural"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "2.5-3 hours",
    notes: "Previously colored mid-shaft may lift unevenly. Watch for hot spots. Consider adding lowlights for dimension."
  },
  {
    beforeHairColor: "Level 8 light blonde, brassy yellow tones",
    beforeHairType: "1A straight, fine, high porosity",
    beforeCondition: "Over-processed, needs toning",
    beforeLevel: "8",
    afterHairColor: "Level 8 cool ash blonde, no brassiness",
    afterLevel: "8",
    technique: "All-over toner and gloss",
    formulaDetails: "No lightening needed. Apply Redken Shades EQ 8V + 8T + Clear (1:1:2) with processing solution. Process 20 min. Follow with Redken Acidic Bonding Concentrate treatment.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["8V", "8T", "Clear"],
    developer: "Processing solution",
    processingTime: "20 min",
    tags: ["toner", "brass-correction", "ash-blonde", "gloss", "quick-service"],
    difficulty: "beginner",
    priceRange: "$",
    estimatedTime: "45 min - 1 hour",
    notes: "Great maintenance service between highlight appointments. Dilute with clear to prevent over-depositing on porous ends."
  },
  {
    beforeHairColor: "Level 3 dark brown, virgin",
    beforeHairType: "2C curly, low porosity",
    beforeCondition: "Virgin hair, resistant cuticle",
    beforeLevel: "3",
    afterHairColor: "Level 6 caramel balayage on dark base",
    afterLevel: "6",
    technique: "Balayage with clay lightener",
    formulaDetails: "Use clay-based lightener (Redken Brews Clay Lightener or L'Oreal Bonder Inside) + 30 vol (1:1). Freehand paint mid-lengths to ends, concentrating on face frame. Wrap in plastic. Process 45 min with low heat. Tone: Shades EQ 6G + 6GB (1:1). Process 20 min.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["6G", "6GB"],
    developer: "30 vol",
    lightener: "Clay lightener",
    toner: "Shades EQ 6G + 6GB",
    additives: ["Olaplex No.1"],
    processingTime: "45 min lightener, 20 min toner",
    tags: ["caramel", "balayage", "curly-hair", "dark-base", "warm-tone"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "3-4 hours",
    notes: "Clay lightener is best for curly hair - stays in place. Low porosity hair needs heat to open cuticle. Don't over-lighten - caramel is the goal, not blonde."
  },
  {
    beforeHairColor: "Level 7 medium blonde with warm tones",
    beforeHairType: "1B straight, medium porosity",
    beforeCondition: "Previously highlighted, 3 months grown out",
    beforeLevel: "7",
    afterHairColor: "Level 10 bright white platinum",
    afterLevel: "10",
    technique: "Double process blonde",
    formulaDetails: "Step 1: Apply Schwarzkopf IGORA Vario Blond Plus + 30 vol (1:2) root to ends. Process under heat 40 min. Must reach level 10 pale yellow. Step 2: Rinse, shampoo, towel dry. Apply Schwarzkopf BlondMe Toning T-Ice + T-Lilac (3:1). Process 10 min. Watch carefully.",
    colorBrand: "Schwarzkopf",
    colorLine: "IGORA / BlondMe",
    colorShades: ["T-Ice", "T-Lilac"],
    developer: "30 vol",
    developerRatio: "1:2",
    lightener: "IGORA Vario Blond Plus",
    toner: "BlondMe T-Ice + T-Lilac",
    additives: ["IGORA Fibrebond"],
    processingTime: "40 min lightener, 10 min toner",
    tags: ["platinum", "white-blonde", "double-process", "schwarzkopf", "high-lift"],
    difficulty: "advanced",
    priceRange: "$$$$",
    estimatedTime: "3-4 hours",
    notes: "Client must understand maintenance commitment. Roots every 4-6 weeks. Must use purple shampoo at home. Bond treatment essential."
  },
  {
    beforeHairColor: "Level 4 dark brown with neutral tones",
    beforeHairType: "2A wavy, medium porosity",
    beforeCondition: "Virgin hair",
    beforeLevel: "4",
    afterHairColor: "Level 7 dimensional bronde (brown-blonde)",
    afterLevel: "7",
    technique: "Foilyage",
    formulaDetails: "Paint Redken Flash Lift + 30 vol (1:2) freehand, then close in foils. Alternate thick and thin sections for dimension. Process 40 min. Tone: Shades EQ 7NB + 7GB + 7V (2:1:0.5). Process 20 min.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["7NB", "7GB", "7V"],
    developer: "30 vol",
    developerRatio: "1:2",
    lightener: "Flash Lift",
    toner: "Shades EQ 7NB + 7GB + 7V",
    additives: ["Olaplex No.1"],
    processingTime: "40 min lightener, 20 min toner",
    tags: ["bronde", "foilyage", "dimensional", "natural", "low-maintenance"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "3-3.5 hours",
    notes: "Foilyage gives more lift than open-air balayage. The touch of violet in the toner prevents brassiness."
  },
  {
    beforeHairColor: "Level 2 near-black, virgin",
    beforeHairType: "3A curly, medium porosity",
    beforeCondition: "Virgin, healthy",
    beforeLevel: "2",
    afterHairColor: "Level 5 warm chestnut highlights on dark base",
    afterLevel: "5",
    technique: "Pintura highlights (curl-by-curl painting)",
    formulaDetails: "Pintura technique: paint individual curls with Redken Flash Lift + 20 vol (1:1). Select curls around face and throughout crown. Let curls hang naturally while painting. Process 35 min open air. Tone: Shades EQ 5G + 5WG (1:1). Process 15 min.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["5G", "5WG"],
    developer: "20 vol",
    lightener: "Flash Lift",
    toner: "Shades EQ 5G + 5WG",
    additives: ["Olaplex No.1"],
    processingTime: "35 min lightener, 15 min toner",
    tags: ["pintura", "curly-hair", "chestnut", "curl-painting", "natural"],
    difficulty: "advanced",
    priceRange: "$$$",
    estimatedTime: "3-4 hours",
    notes: "Pintura is specifically designed for curly hair. Paint on the outside of each curl spring for maximum visibility. Subtle lift is the goal."
  },
  {
    beforeHairColor: "Level 6 light brown with golden tones",
    beforeHairType: "1C straight, coarse, low porosity",
    beforeCondition: "Virgin hair, resistant",
    beforeLevel: "6",
    afterHairColor: "Level 9 bright butter blonde all-over",
    afterLevel: "9",
    technique: "High-lift color",
    formulaDetails: "Use Wella Koleston Perfect Special Blonde 12/07 + 12/03 (1:1) with 40 vol (1:2). Apply root to ends on dry unwashed hair. Process 50 min with heat cap. If not light enough, follow with Shades EQ 9N + 9GI (1:1) gloss.",
    colorBrand: "Wella",
    colorLine: "Koleston Perfect Special Blonde",
    colorShades: ["12/07", "12/03"],
    developer: "40 vol",
    developerRatio: "1:2",
    toner: "Shades EQ 9N + 9GI if needed",
    processingTime: "50 min with heat",
    tags: ["high-lift", "butter-blonde", "all-over", "wella", "single-process"],
    difficulty: "intermediate",
    priceRange: "$$",
    estimatedTime: "2-2.5 hours",
    notes: "High-lift color only works on virgin hair levels 5-7. Will not work on previously colored hair. 40 vol is necessary for maximum lift."
  },
  {
    beforeHairColor: "Level 8 blonde with orange brassiness",
    beforeHairType: "2B wavy, high porosity",
    beforeCondition: "Previously bleached, damaged, brassy",
    beforeLevel: "8",
    afterHairColor: "Level 8 pearl blonde with cool undertone",
    afterLevel: "8",
    technique: "Purple shampoo treatment + toner",
    formulaDetails: "Step 1: Wash with Redken Color Extend Blondage purple shampoo, leave 5 min. Step 2: Apply Redken Shades EQ 9P + 9V + Clear (1:1:2) with processing solution. Process 15 min. Step 3: Follow with K18 leave-in treatment.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["9P", "9V", "Clear"],
    developer: "Processing solution",
    additives: ["K18 Leave-in"],
    processingTime: "5 min purple shampoo, 15 min toner",
    tags: ["brass-correction", "pearl-blonde", "toner", "damaged-hair", "repair"],
    difficulty: "beginner",
    priceRange: "$",
    estimatedTime: "45 min",
    notes: "Porous hair grabs violet fast - dilute with clear and watch timing. K18 is essential for repairing bond damage."
  },
  {
    beforeHairColor: "Level 5 medium brown, natural",
    beforeHairType: "1A straight, fine",
    beforeCondition: "Virgin, fine hair",
    beforeLevel: "5",
    afterHairColor: "Level 8 bright blonde money piece with face-frame highlights",
    afterLevel: "8",
    technique: "Money piece with partial highlights",
    formulaDetails: "Section out 1.5 inch face frame pieces. Add partial foils through crown. Schwarzkopf BlondMe Premium Lift 9+ with 20 vol (1:1.5). Process 35 min. Tone: BlondMe Toning T-Sand + T-Apricot (2:1). Process 10 min.",
    colorBrand: "Schwarzkopf",
    colorLine: "BlondMe",
    colorShades: ["T-Sand", "T-Apricot"],
    developer: "20 vol",
    developerRatio: "1:1.5",
    lightener: "BlondMe Premium Lift 9+",
    toner: "BlondMe T-Sand + T-Apricot",
    additives: ["BlondMe Bond Enforcing"],
    processingTime: "35 min lightener, 10 min toner",
    tags: ["money-piece", "face-frame", "partial-foil", "warm-blonde", "fine-hair"],
    difficulty: "beginner",
    priceRange: "$$",
    estimatedTime: "2-2.5 hours",
    notes: "Fine hair lifts faster - check every 10 min. The warm toner prevents looking washed out on fair skin."
  },
  // ─── RED / COPPER VARIATIONS (26-35) ────────────────────
  {
    beforeHairColor: "Level 6 medium brown with neutral tones",
    beforeHairType: "2A wavy, medium porosity",
    beforeCondition: "Virgin hair",
    beforeLevel: "6",
    afterHairColor: "Level 6 deep auburn red",
    afterLevel: "6",
    technique: "All-over permanent color",
    formulaDetails: "Wella Koleston Perfect 6/45 + 6/4 (2:1) with 20 vol (1:1). Apply root to ends. Process 35 min. Emulsify well before rinsing.",
    colorBrand: "Wella",
    colorLine: "Koleston Perfect",
    colorShades: ["6/45", "6/4"],
    developer: "20 vol",
    developerRatio: "1:1",
    processingTime: "35 min",
    tags: ["auburn", "red", "permanent", "all-over", "wella", "warm-tone"],
    difficulty: "beginner",
    priceRange: "$$",
    estimatedTime: "1.5-2 hours",
    notes: "Auburn is one of the easiest reds to maintain. Recommend color-safe sulfate-free shampoo."
  },
  {
    beforeHairColor: "Level 8 light blonde, previously highlighted",
    beforeHairType: "1B straight, high porosity",
    beforeCondition: "Previously bleached, porous",
    beforeLevel: "8",
    afterHairColor: "Level 7 strawberry blonde",
    afterLevel: "7",
    technique: "Color fill + permanent color",
    formulaDetails: "Step 1: Fill with Redken Shades EQ 8GI (gold iridescent) - process 10 min, do NOT rinse. Step 2: Apply Wella Koleston Perfect 7/34 + 7/43 (1:1) with 10 vol (1:1) over the filler. Process 25 min.",
    colorBrand: "Wella",
    colorLine: "Koleston Perfect",
    colorShades: ["7/34", "7/43"],
    developer: "10 vol",
    developerRatio: "1:1",
    toner: "Pre-fill with Shades EQ 8GI",
    processingTime: "10 min fill, 25 min color",
    tags: ["strawberry-blonde", "color-fill", "going-darker", "warm-tone", "porous-hair"],
    difficulty: "intermediate",
    priceRange: "$$",
    estimatedTime: "2 hours",
    notes: "MUST fill first when going from blonde to red/warm. Without filler, color will fade in 1-2 washes. Porous hair needs 10 vol only."
  },
  {
    beforeHairColor: "Level 4 dark brown, natural",
    beforeHairType: "2B wavy, medium porosity",
    beforeCondition: "Virgin hair",
    beforeLevel: "4",
    afterHairColor: "Level 5 rich burgundy wine red",
    afterLevel: "5",
    technique: "All-over permanent with red intensifier",
    formulaDetails: "Wella Koleston Perfect 5/5 + 55/65 (3:1) with 20 vol (1:1). The 55/65 is a pure pigment booster for extra vibrancy. Apply root to ends. Process 35 min with plastic cap.",
    colorBrand: "Wella",
    colorLine: "Koleston Perfect",
    colorShades: ["5/5", "55/65"],
    developer: "20 vol",
    developerRatio: "1:1",
    processingTime: "35 min under plastic cap",
    tags: ["burgundy", "wine-red", "permanent", "vibrant", "wella"],
    difficulty: "beginner",
    priceRange: "$$",
    estimatedTime: "1.5-2 hours",
    notes: "The pure pigment booster (55/65) adds intense vibrancy. Red fades fastest of all colors - recommend cool water and color-safe products."
  },
  {
    beforeHairColor: "Level 7 dark blonde, natural",
    beforeHairType: "2A wavy, medium porosity",
    beforeCondition: "Virgin, healthy",
    beforeLevel: "7",
    afterHairColor: "Level 7 fiery bright copper",
    afterLevel: "7",
    technique: "All-over permanent color",
    formulaDetails: "Joico LumiShine 7NC + 7CC (1:1) with 20 vol (1:1). Apply to roots first, process 20 min, then pull through to ends for remaining 15 min.",
    colorBrand: "Joico",
    colorLine: "LumiShine",
    colorShades: ["7NC", "7CC"],
    developer: "20 vol",
    developerRatio: "1:1",
    processingTime: "35 min total (20 root, 15 pull-through)",
    tags: ["copper", "bright-red", "joico", "permanent", "vibrant"],
    difficulty: "beginner",
    priceRange: "$$",
    estimatedTime: "1.5 hours",
    notes: "The double copper (7CC) boosts intensity. Apply to roots first since they need more processing time."
  },
  {
    beforeHairColor: "Level 3 dark brown with warm undertones",
    beforeHairType: "2C curly, medium-high porosity",
    beforeCondition: "Previously colored, some dryness",
    beforeLevel: "3",
    afterHairColor: "Level 5 cherry red highlights on dark base",
    afterLevel: "5",
    technique: "Chunky foil highlights with red color",
    formulaDetails: "Take chunky diagonal sections through top and sides. Lightener: Redken Flash Lift + 20 vol (1:1). Process 30 min to reach level 7 (need underlying warmth for red). Color highlighted sections: Wella Koleston 5/66 + 0/45 (4:1) with 10 vol. Process 20 min.",
    colorBrand: "Wella",
    colorLine: "Koleston Perfect",
    colorShades: ["5/66", "0/45"],
    developer: "20 vol lightener, 10 vol color",
    lightener: "Flash Lift",
    additives: ["Olaplex No.1"],
    processingTime: "30 min lightener, 20 min color",
    tags: ["cherry-red", "chunky-highlights", "curly", "bold", "contrast"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "3-3.5 hours",
    notes: "Don't lift past level 7 - you need the warm undertone for the red to look vibrant. The pure pigment 0/45 intensifies the red."
  },
  {
    beforeHairColor: "Level 5 brown with previous red color fading",
    beforeHairType: "1B straight, medium porosity",
    beforeCondition: "Previous red color faded to orange-brown",
    beforeLevel: "5",
    afterHairColor: "Level 6 rich copper penny",
    afterLevel: "6",
    technique: "Copper color refresh",
    formulaDetails: "Apply Redken Shades EQ 6RR + 6C + 6G (2:1:1) with processing solution. Process 20 min. No lightening needed - building on existing warm base.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["6RR", "6C", "6G"],
    developer: "Processing solution",
    processingTime: "20 min",
    tags: ["copper", "color-refresh", "demi-permanent", "quick-service", "warm-tone"],
    difficulty: "beginner",
    priceRange: "$",
    estimatedTime: "45 min - 1 hour",
    notes: "Working with existing warm undertones. The gold (6G) adds dimension and prevents the red from looking flat."
  },
  // ─── GREY COVERAGE VARIATIONS (36-50) ───────────────────
  {
    beforeHairColor: "Level 5 medium brown with 30% grey",
    beforeHairType: "1C straight, coarse, low porosity",
    beforeCondition: "Resistant grey, coarse texture",
    beforeLevel: "5",
    afterHairColor: "Level 5 natural brown with full grey coverage",
    afterLevel: "5",
    technique: "Permanent grey coverage",
    formulaDetails: "Pre-soften grey-concentrated areas with 10 vol for 10 min, blot. Apply Wella Koleston Perfect 5/0 + 5/03 (1:1) with 10 vol (1:1). Apply to grey areas first, then remaining hair. Process 35 min.",
    colorBrand: "Wella",
    colorLine: "Koleston Perfect",
    colorShades: ["5/0", "5/03"],
    developer: "10 vol",
    developerRatio: "1:1",
    processingTime: "10 min pre-soften, 35 min color",
    tags: ["grey-coverage", "brunette", "natural", "permanent", "wella"],
    difficulty: "beginner",
    priceRange: "$$",
    estimatedTime: "1.5-2 hours",
    notes: "The 5/0 (pure base) provides maximum grey coverage. 5/03 adds warmth to prevent ashy results on grey. Use 10 vol for better deposit on grey hair."
  },
  {
    beforeHairColor: "Level 7 dark blonde with 70% grey",
    beforeHairType: "1A straight, fine, medium porosity",
    beforeCondition: "Predominantly grey, fine texture",
    beforeLevel: "7",
    afterHairColor: "Level 8 cool blonde blend covering grey",
    afterLevel: "8",
    technique: "Grey blending with highlights",
    formulaDetails: "Weave fine highlights throughout with Wella Blondor + 20 vol (1:2). Process 30 min. Tone all over: Shades EQ 8V + 8GI + Clear (1:1:1) with processing solution. Process 15 min. The grey hairs become platinum highlights.",
    colorBrand: "Wella / Redken",
    colorLine: "Blondor / Shades EQ",
    colorShades: ["8V", "8GI", "Clear"],
    developer: "20 vol",
    developerRatio: "1:2",
    lightener: "Wella Blondor",
    toner: "Shades EQ 8V + 8GI + Clear",
    processingTime: "30 min lightener, 15 min toner",
    tags: ["grey-blending", "highlights", "blonde", "low-maintenance", "natural"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "2.5-3 hours",
    notes: "Grey blending is the modern alternative to full coverage. Grey hairs blend seamlessly with highlights. Grows out beautifully."
  },
  {
    beforeHairColor: "Level 4 dark brown with 80% grey at temples",
    beforeHairType: "2A wavy, medium porosity",
    beforeCondition: "Heavy grey concentration at hairline and temples",
    beforeLevel: "4",
    afterHairColor: "Level 4 dark brown with natural grey blend",
    afterLevel: "4",
    technique: "Grey camouflage with demi-permanent",
    formulaDetails: "Apply Redken Shades EQ 4N + 4NA (2:1) with processing solution. Focus on temple and hairline areas. Process 20 min. This softens grey by 50% rather than full coverage for a more natural look.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["4N", "4NA"],
    developer: "Processing solution",
    processingTime: "20 min",
    tags: ["grey-camouflage", "demi-permanent", "natural", "low-commitment", "men-friendly"],
    difficulty: "beginner",
    priceRange: "$",
    estimatedTime: "45 min",
    notes: "Demi-permanent doesn't fully cover grey - it blends 50%. Perfect for clients who want a natural look. Fades in 6-8 weeks."
  },
  {
    beforeHairColor: "Level 6 medium brown with 40% grey scattered",
    beforeHairType: "1B straight, medium texture",
    beforeCondition: "Grey scattered throughout, medium density",
    beforeLevel: "6",
    afterHairColor: "Level 6 warm brown with seamless grey coverage",
    afterLevel: "6",
    technique: "Permanent color with warm base",
    formulaDetails: "Apply Joico LumiShine 6NWB with 10 vol (1:1). The warm brown base provides natural-looking grey coverage. Apply to new growth first, process 25 min, pull through to ends for 10 min.",
    colorBrand: "Joico",
    colorLine: "LumiShine",
    colorShades: ["6NWB"],
    developer: "10 vol",
    developerRatio: "1:1",
    processingTime: "25 min root, 10 min ends",
    tags: ["grey-coverage", "warm-brown", "permanent", "joico", "natural"],
    difficulty: "beginner",
    priceRange: "$$",
    estimatedTime: "1.5 hours",
    notes: "LumiShine's built-in ArgiPlex reduces damage. Warm bases cover grey more naturally than cool tones. Use 10 vol for optimal grey deposit."
  },
  {
    beforeHairColor: "Level 3 dark brown with 60% grey",
    beforeHairType: "2B wavy, medium porosity",
    beforeCondition: "Significant grey growth, 6 weeks since last color",
    beforeLevel: "3",
    afterHairColor: "Level 4 dark chocolate with grey coverage",
    afterLevel: "4",
    technique: "Root touch-up with full grey coverage",
    formulaDetails: "Apply Wella Koleston Perfect 4/07 + 4/0 (1:1) with 10 vol (1:1) to new growth only. Process 35 min. For last 5 min, emulsify through mid-lengths and ends to refresh.",
    colorBrand: "Wella",
    colorLine: "Koleston Perfect",
    colorShades: ["4/07", "4/0"],
    developer: "10 vol",
    developerRatio: "1:1",
    processingTime: "35 min root, 5 min pull-through",
    tags: ["root-touch-up", "grey-coverage", "dark-brown", "permanent", "maintenance"],
    difficulty: "beginner",
    priceRange: "$$",
    estimatedTime: "1-1.5 hours",
    notes: "4/07 adds warmth to prevent flatness on grey. Only pull through ends for refresh - over-processing causes buildup. Use 10 vol for grey deposit."
  },
  {
    beforeHairColor: "Level 5 medium brown with 90% grey",
    beforeHairType: "1C straight, coarse",
    beforeCondition: "Almost fully grey, resistant, wiry texture",
    beforeLevel: "5",
    afterHairColor: "Level 5 rich espresso with 100% grey coverage",
    afterLevel: "5",
    technique: "Maximum grey coverage protocol",
    formulaDetails: "Pre-soften with 10 vol for 15 min on resistant areas, blot. Apply Wella Koleston Perfect 5/0 + 5/07 + 4/0 (2:1:0.5) with 10 vol (1:1). Apply to most resistant areas first. Process 40 min. Emulsify 2 min before rinse.",
    colorBrand: "Wella",
    colorLine: "Koleston Perfect",
    colorShades: ["5/0", "5/07", "4/0"],
    developer: "10 vol",
    developerRatio: "1:1",
    processingTime: "15 min pre-soften, 40 min color",
    tags: ["grey-coverage", "resistant-grey", "espresso", "permanent", "maximum-coverage"],
    difficulty: "intermediate",
    priceRange: "$$",
    estimatedTime: "2 hours",
    notes: "Triple base formula ensures maximum coverage. The half part of 4/0 deepens the result and anchors color. Pre-softening is mandatory for resistant grey. Always use 10 vol on grey."
  },
  {
    beforeHairColor: "Level 7 blonde with 50% silver-white grey",
    beforeHairType: "1A straight, fine",
    beforeCondition: "Salt and pepper, embracing natural texture",
    beforeLevel: "7",
    afterHairColor: "Level 9 bright silver-grey with dimension",
    afterLevel: "9",
    technique: "Silver grey enhancement",
    formulaDetails: "Light highlights with Wella Blondor + 20 vol (1:2) on darker sections only. Process 25 min. Tone all over with Wella Color Touch 8/81 + 0/88 (4:1) with 4% emulsion. Process 15 min. Creates intentional silver.",
    colorBrand: "Wella",
    colorLine: "Color Touch",
    colorShades: ["8/81", "0/88"],
    developer: "4% emulsion",
    lightener: "Wella Blondor",
    toner: "Color Touch 8/81 + 0/88",
    processingTime: "25 min lightener, 15 min toner",
    tags: ["silver", "grey-enhancement", "embracing-grey", "modern", "dimensional"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "2.5 hours",
    notes: "This technique works WITH the grey rather than covering it. Only lighten the remaining dark hair to match. The blue-violet toner creates intentional silver."
  },
  {
    beforeHairColor: "Level 4 dark brown with 25% grey at temples",
    beforeHairType: "2A wavy, medium porosity",
    beforeCondition: "Early greying, concentrated at hairline",
    beforeLevel: "4",
    afterHairColor: "Level 5 warm brown with face-frame highlights blending grey",
    afterLevel: "5",
    technique: "Grey-blending face frame highlights",
    formulaDetails: "Face frame babylights with Redken Flash Lift + 20 vol (1:1.5). Process 30 min. Tone face frame: Shades EQ 7GB + Clear (1:1). Process 10 min. Base color on remaining: Shades EQ 4N + 4WG (2:1). Process 20 min.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["7GB", "Clear", "4N", "4WG"],
    developer: "20 vol highlights, processing solution base",
    lightener: "Flash Lift",
    toner: "Shades EQ multi-formula",
    processingTime: "30 min lightener, 20 min base color",
    tags: ["grey-blending", "face-frame", "babylights", "natural", "warm-brown"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "2.5-3 hours",
    notes: "Highlights around the face blend the grey naturally. The base gloss softens remaining grey without full coverage. Low maintenance option."
  },
  {
    beforeHairColor: "Level 6 medium brown with 45% grey roots, 2 inch regrowth",
    beforeHairType: "1B straight, medium porosity",
    beforeCondition: "Regular color client, 8 weeks since last appointment",
    beforeLevel: "6",
    afterHairColor: "Level 6 natural brown with grey coverage and subtle warmth",
    afterLevel: "6",
    technique: "Root retouch with grey coverage",
    formulaDetails: "Apply L'Oreal Majirel 6.03 + 6.0 (1:1) with 10 vol (1:1) to new growth only. Process 35 min. Mist lengths and ends with water, apply Dia Light 6.13 for 5 min refresh.",
    colorBrand: "L'Oreal",
    colorLine: "Majirel / Dia Light",
    colorShades: ["6.03", "6.0", "6.13"],
    developer: "10 vol root, Dia developer ends",
    developerRatio: "1:1",
    processingTime: "35 min root, 5 min refresh",
    tags: ["root-retouch", "grey-coverage", "loreal", "maintenance", "natural-brown"],
    difficulty: "beginner",
    priceRange: "$$",
    estimatedTime: "1-1.5 hours",
    notes: "Dia Light on the ends refreshes without buildup. Never apply permanent color to previously colored lengths every visit - causes darkness and damage. Use 10 vol for grey."
  },
  // ─── BRUNETTE VARIATIONS (51-60) ────────────────────────
  {
    beforeHairColor: "Level 7 dark blonde with warm yellow tones",
    beforeHairType: "2A wavy, medium porosity",
    beforeCondition: "Previously highlighted, wants to go darker",
    beforeLevel: "7",
    afterHairColor: "Level 4 rich dark chocolate",
    afterLevel: "4",
    technique: "Going darker with color fill",
    formulaDetails: "Step 1: Fill with Redken Shades EQ 6GI + 6G (1:1) with processing solution. Process 10 min, do NOT rinse. Step 2: Apply Wella Koleston Perfect 4/07 + 4/77 (2:1) with 10 vol over filler. Process 30 min.",
    colorBrand: "Wella",
    colorLine: "Koleston Perfect",
    colorShades: ["4/07", "4/77"],
    developer: "10 vol",
    developerRatio: "1:1",
    toner: "Pre-fill: Shades EQ 6GI + 6G",
    processingTime: "10 min fill, 30 min color",
    tags: ["going-darker", "chocolate", "color-fill", "brunette", "permanent"],
    difficulty: "intermediate",
    priceRange: "$$",
    estimatedTime: "2 hours",
    notes: "MUST fill when going more than 2 levels darker. Without filling, color will wash out and look green/ashy. The gold filler replaces missing warm pigment."
  },
  {
    beforeHairColor: "Level 3 dark brown, natural",
    beforeHairType: "3B curly, high porosity",
    beforeCondition: "Natural curly, some dryness at ends",
    beforeLevel: "3",
    afterHairColor: "Level 4 dimensional chocolate with warm lowlights",
    afterLevel: "4",
    technique: "Demi-permanent gloss for dimension",
    formulaDetails: "Apply Redken Shades EQ 4WG on alternating sections, 3WG on remaining. Use weaving technique but with color instead of lightener. Process 20 min. Finish with deep conditioner.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["4WG", "3WG"],
    developer: "Processing solution",
    processingTime: "20 min",
    tags: ["dimensional", "chocolate", "curly-hair", "demi-permanent", "glossy"],
    difficulty: "beginner",
    priceRange: "$",
    estimatedTime: "1-1.5 hours",
    notes: "Adds beautiful dimension without lightening. Curly hair shows dimension more than straight hair. The warm tones enhance curl definition visually."
  },
  {
    beforeHairColor: "Level 6 light brown, flat single-process color",
    beforeHairType: "1B straight, medium porosity",
    beforeCondition: "Previously colored same shade for years, no dimension",
    beforeLevel: "6",
    afterHairColor: "Level 6 dimensional rich brunette with caramel ribbons",
    afterLevel: "6",
    technique: "Lowlights and highlights for dimension",
    formulaDetails: "Lowlights: Wella Koleston 4/07 with 10 vol in fine foils. Highlights: Redken Flash Lift + 20 vol in alternating foils. Process 30 min. Tone all: Shades EQ 6NBr + 6GB (2:1). Process 20 min.",
    colorBrand: "Redken / Wella",
    colorLine: "Shades EQ / Koleston",
    colorShades: ["6NBr", "6GB", "4/07"],
    developer: "10 vol lowlights, 20 vol highlights",
    lightener: "Flash Lift",
    processingTime: "30 min foils, 20 min toner",
    tags: ["dimensional", "lowlights", "highlights", "caramel", "brunette-enhancement"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "3-3.5 hours",
    notes: "Lowlights add depth while highlights add brightness. Together they break up flat single-process color beautifully."
  },
  {
    beforeHairColor: "Level 8 grown-out blonde, dark regrowth",
    beforeHairType: "1A straight, fine",
    beforeCondition: "Blonde wanting to return to natural brunette",
    beforeLevel: "8",
    afterHairColor: "Level 5 warm espresso brown",
    afterLevel: "5",
    technique: "Blonde to brunette with fill and permanent",
    formulaDetails: "Step 1: Fill porous ends with Redken Shades EQ 7GI with processing solution, process 10 min, blot. Step 2: Apply L'Oreal Majirel 5.35 + 5.03 (1:1) with 10 vol (1:1) root to ends. Process 30 min. Step 3: Emulsify and check. May need second application on resistant blonde ends.",
    colorBrand: "L'Oreal",
    colorLine: "Majirel",
    colorShades: ["5.35", "5.03"],
    developer: "10 vol",
    developerRatio: "1:1",
    toner: "Pre-fill: Shades EQ 7GI",
    processingTime: "10 min fill, 30 min color",
    tags: ["blonde-to-brunette", "color-fill", "espresso", "going-darker", "transition"],
    difficulty: "intermediate",
    priceRange: "$$",
    estimatedTime: "2-2.5 hours",
    notes: "Going from blonde to brunette always requires filling. Expect the color to fade 1-2 levels after first wash. Schedule a gloss refresh in 2 weeks."
  },
  {
    beforeHairColor: "Level 4 dark brown with orange bands from previous lightening",
    beforeHairType: "2A wavy, medium porosity",
    beforeCondition: "Banded color from DIY attempts",
    beforeLevel: "4",
    afterHairColor: "Level 4 uniform dark brown, corrected banding",
    afterLevel: "4",
    technique: "Color correction - banding removal",
    formulaDetails: "Apply Redken Shades EQ 4NA on orange bands only. Process 20 min. Then apply Shades EQ 4N + 4WG (2:1) all-over root to ends. Process 20 min. The ash on the bands neutralizes the orange.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["4NA", "4N", "4WG"],
    developer: "Processing solution",
    processingTime: "20 min spot, 20 min all-over",
    tags: ["color-correction", "banding", "brunette", "fix", "demi-permanent"],
    difficulty: "intermediate",
    priceRange: "$$",
    estimatedTime: "1.5-2 hours",
    notes: "Ash neutralizes orange. Apply ash formula to bands FIRST, then all-over color. Multiple sessions may be needed for severe banding."
  },
  {
    beforeHairColor: "Level 2 near-black, natural",
    beforeHairType: "1C straight, coarse, low porosity",
    beforeCondition: "Virgin, very dark, Asian hair type",
    beforeLevel: "2",
    afterHairColor: "Level 3 soft black with subtle warm reflect",
    afterLevel: "3",
    technique: "Demi-permanent gloss for shine",
    formulaDetails: "Apply Redken Shades EQ 3G + 3N (1:1) with processing solution. Process 20 min under plastic cap with heat. The warm gold reflect adds dimension to near-black hair.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["3G", "3N"],
    developer: "Processing solution",
    processingTime: "20 min with heat",
    tags: ["gloss", "near-black", "shine", "subtle", "asian-hair", "warm-reflect"],
    difficulty: "beginner",
    priceRange: "$",
    estimatedTime: "45 min - 1 hour",
    notes: "Even the darkest hair benefits from a gloss. The warm reflect creates incredible shine and dimension in sunlight. Heat helps low-porosity hair absorb color."
  },
  // ─── COLOR CORRECTIONS (61-70) ──────────────────────────
  {
    beforeHairColor: "Level 6 green-tinted brown from box dye over highlights",
    beforeHairType: "1B straight, high porosity",
    beforeCondition: "Green cast from ash box dye over warm blonde",
    beforeLevel: "6",
    afterHairColor: "Level 6 neutral warm brown, no green",
    afterLevel: "6",
    technique: "Color correction - green neutralization",
    formulaDetails: "Apply Wella Koleston Perfect 6/43 + 0/34 (3:1) with 10 vol (1:1). The red-copper pigment neutralizes green. Process 30 min. Follow with Shades EQ 6N + 6WG (1:1) all-over for even finish. Process 15 min.",
    colorBrand: "Wella",
    colorLine: "Koleston Perfect / Shades EQ",
    colorShades: ["6/43", "0/34", "6N", "6WG"],
    developer: "10 vol permanent, processing solution gloss",
    processingTime: "30 min correction, 15 min gloss",
    tags: ["color-correction", "green-neutralize", "box-dye-fix", "warm-brown"],
    difficulty: "advanced",
    priceRange: "$$$",
    estimatedTime: "2.5-3 hours",
    notes: "Red neutralizes green on the color wheel. The 0/34 pure pigment is key. May need multiple sessions if green is deep in the cortex."
  },
  {
    beforeHairColor: "Level 9 very light blonde with pink/purple staining",
    beforeHairType: "2A wavy, high porosity",
    beforeCondition: "Fashion color staining from previous purple/pink",
    beforeLevel: "9",
    afterHairColor: "Level 9 clean neutral blonde",
    afterLevel: "9",
    technique: "Color correction - fashion color removal",
    formulaDetails: "Step 1: Vitamin C treatment - mix crushed vitamin C tablets with clarifying shampoo to paste. Apply to stained areas, wrap in plastic, sit 30 min. Rinse. Step 2: If stain persists, apply Malibu C DDL treatment. Process 15 min. Step 3: Tone with Shades EQ 9N + Clear (1:3). Process 10 min.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["9N", "Clear"],
    developer: "Processing solution",
    additives: ["Vitamin C", "Malibu C DDL"],
    processingTime: "30 min vitamin C, 15 min DDL, 10 min toner",
    tags: ["color-correction", "fashion-color-removal", "stain-removal", "blonde"],
    difficulty: "intermediate",
    priceRange: "$$",
    estimatedTime: "2-3 hours",
    notes: "Fashion color stains are not the same as permanent color. Vitamin C is surprisingly effective. Do NOT use bleach - it can set the stain permanently."
  },
  {
    beforeHairColor: "Level 7 uneven blonde with dark bands and hot roots",
    beforeHairType: "1B straight, mixed porosity",
    beforeCondition: "Uneven color from multiple salon visits",
    beforeLevel: "7",
    afterHairColor: "Level 8 even, seamless blonde",
    afterLevel: "8",
    technique: "Color correction - evening out blonde",
    formulaDetails: "Map the head into zones based on current level. Zone 1 (dark bands): Redken Flash Lift + 20 vol in foils. Zone 2 (hot roots): Shades EQ 8N + 8V (1:1) deposit only. Zone 3 (correct areas): leave alone. Process zones simultaneously 25 min. Then tone all: Shades EQ 8GI + 8V + Clear (1:1:1). Process 15 min.",
    colorBrand: "Redken",
    colorLine: "Flash Lift / Shades EQ",
    colorShades: ["8N", "8V", "8GI", "Clear"],
    developer: "20 vol lightener, processing solution toner",
    lightener: "Flash Lift",
    toner: "Shades EQ multi-zone",
    additives: ["Olaplex No.1"],
    processingTime: "25 min zones, 15 min toner",
    tags: ["color-correction", "even-blonde", "zone-coloring", "hot-roots", "banding"],
    difficulty: "advanced",
    priceRange: "$$$$",
    estimatedTime: "3-4 hours",
    notes: "Zone coloring is key - different formulas for different areas. Never apply the same formula everywhere when correcting. Requires precise mapping."
  },
  {
    beforeHairColor: "Level 5 brown with orange streaks from sun damage",
    beforeHairType: "2B wavy, high porosity",
    beforeCondition: "Sun-damaged, uneven warm tones",
    beforeLevel: "5",
    afterHairColor: "Level 5 rich cool brown, even tone",
    afterLevel: "5",
    technique: "Tone correction with demi-permanent",
    formulaDetails: "Apply Redken Shades EQ 5NA + 5N (2:1) with processing solution. The extra ash neutralizes the warm/orange areas. Process 20 min. Follow with deep conditioning treatment.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["5NA", "5N"],
    developer: "Processing solution",
    processingTime: "20 min",
    tags: ["tone-correction", "cool-brown", "ash", "sun-damage", "even-tone"],
    difficulty: "beginner",
    priceRange: "$",
    estimatedTime: "45 min - 1 hour",
    notes: "Ash formulas neutralize unwanted warmth. Don't go too heavy on ash or hair will look muddy. The 2:1 ratio is enough for moderate warmth."
  },
  {
    beforeHairColor: "Level 4 dark brown with jet black box dye on lengths",
    beforeHairType: "2A wavy, low porosity on lengths",
    beforeCondition: "Box dye buildup, line of demarcation at 3 inches",
    beforeLevel: "4",
    afterHairColor: "Level 5 uniform medium-dark brown",
    afterLevel: "5",
    technique: "Color correction - line of demarcation blending",
    formulaDetails: "New growth: Wella Koleston Perfect 5/07 + 5/03 (1:1) with 20 vol. Process 30 min. Line of demarcation area: spot apply Colour Remover (Joico Color Eraser), process 15 min. Lengths: leave or apply Shades EQ 4N to refresh. Blend at demarcation with teasing technique.",
    colorBrand: "Wella / Joico",
    colorLine: "Koleston Perfect",
    colorShades: ["5/07", "5/03"],
    developer: "20 vol root, color remover mid",
    developerRatio: "1:1",
    processingTime: "30 min root, 15 min remover",
    tags: ["color-correction", "line-of-demarcation", "box-dye", "blending", "brunette"],
    difficulty: "advanced",
    priceRange: "$$$",
    estimatedTime: "3-4 hours",
    notes: "Do NOT lighten box-dyed lengths with bleach - it won't lift properly and will cause damage. Color remover breaks down artificial pigment. Multiple sessions recommended."
  },
  // ─── OMBRE / SOMBRE / COLOR MELT (71-80) ───────────────
  {
    beforeHairColor: "Level 3 dark brown, natural",
    beforeHairType: "1C straight, medium porosity",
    beforeCondition: "Virgin hair, healthy",
    beforeLevel: "3",
    afterHairColor: "Level 3 root melting to level 7 warm caramel ends",
    afterLevel: "7",
    technique: "Ombre",
    formulaDetails: "Section into 4 quadrants. Backcomb above desired transition point. Apply Redken Flash Lift + 30 vol (1:2) from mid-lengths to ends, heavier saturation at ends. Process 40 min. Tone: Shades EQ 7GB + 7G (1:1). Process 20 min.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["7GB", "7G"],
    developer: "30 vol",
    developerRatio: "1:2",
    lightener: "Flash Lift",
    toner: "Shades EQ 7GB + 7G",
    additives: ["Olaplex No.1"],
    processingTime: "40 min lightener, 20 min toner",
    tags: ["ombre", "caramel", "dark-to-light", "natural-root", "warm-tone"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "3-3.5 hours",
    notes: "Backcombing creates the soft transition. Saturate ends more heavily for maximum lightness. The natural root means zero maintenance at the top."
  },
  {
    beforeHairColor: "Level 4 dark brown, previously colored",
    beforeHairType: "2A wavy, medium porosity",
    beforeCondition: "Previously colored level 4, 3 months growth",
    beforeLevel: "4",
    afterHairColor: "Level 4 base melting to level 6 soft brown sombre",
    afterLevel: "6",
    technique: "Sombre (subtle ombre)",
    formulaDetails: "Freehand paint Redken Flash Lift + 20 vol (1:1.5) on lower third of hair only. Feather up slightly at random. Process 30 min. Tone: Shades EQ 6N + 6WG (2:1). Process 15 min.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["6N", "6WG"],
    developer: "20 vol",
    developerRatio: "1:1.5",
    lightener: "Flash Lift",
    toner: "Shades EQ 6N + 6WG",
    processingTime: "30 min lightener, 15 min toner",
    tags: ["sombre", "subtle", "brunette", "low-maintenance", "natural"],
    difficulty: "beginner",
    priceRange: "$$",
    estimatedTime: "2-2.5 hours",
    notes: "Sombre is only 1-2 levels lighter than the base - ultra natural. Perfect first-time color client. Very low maintenance."
  },
  {
    beforeHairColor: "Level 2 near-black",
    beforeHairType: "3A curly, medium porosity",
    beforeCondition: "Virgin hair",
    beforeLevel: "2",
    afterHairColor: "Level 2 base melting through level 4 to level 6 honey ends",
    afterLevel: "6",
    technique: "Color melt on curly hair",
    formulaDetails: "Paint curls individually (Pintura style). Use Schwarzkopf BlondMe + 30 vol (1:1.5). Heavier on bottom curls, lighter on top. Process 40 min open air. Tone bottom: BlondMe T-Caramel. Tone mid: BlondMe T-Sand + T-Caramel (1:1). Process 15 min.",
    colorBrand: "Schwarzkopf",
    colorLine: "BlondMe",
    colorShades: ["T-Caramel", "T-Sand"],
    developer: "30 vol",
    developerRatio: "1:1.5",
    lightener: "BlondMe",
    toner: "BlondMe multi-tone",
    additives: ["BlondMe Bond Enforcing"],
    processingTime: "40 min lightener, 15 min toner",
    tags: ["color-melt", "curly-hair", "honey", "pintura", "multi-tone"],
    difficulty: "advanced",
    priceRange: "$$$$",
    estimatedTime: "4-5 hours",
    notes: "Curly color melts are stunning but time-intensive. Each curl is individually painted. The color shifts beautifully as curls move."
  },
  {
    beforeHairColor: "Level 5 medium brown",
    beforeHairType: "1B straight, medium porosity",
    beforeCondition: "Previously colored, good condition",
    beforeLevel: "5",
    afterHairColor: "Level 5 root melting to level 8 smoky silver ends",
    afterLevel: "8",
    technique: "Silver ombre",
    formulaDetails: "Balayage with Redken Flash Lift + 30 vol (1:2). Must lift to level 10 pale yellow. Process 45 min. First tone: Shades EQ 9B + 9V (1:1) on lifted sections. Process 15 min. Root melt: Shades EQ 5N at root, feather into lightened area.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["9B", "9V", "5N"],
    developer: "30 vol lightener, processing solution toner",
    developerRatio: "1:2",
    lightener: "Flash Lift",
    toner: "Shades EQ 9B + 9V, root melt 5N",
    additives: ["Olaplex No.1"],
    processingTime: "45 min lightener, 15 min toner",
    tags: ["silver-ombre", "smoky", "fashion-color", "root-melt", "trendy"],
    difficulty: "advanced",
    priceRange: "$$$$",
    estimatedTime: "4-5 hours",
    notes: "Must reach level 10 for silver to read properly. Any remaining yellow will make it look green/muddy. May need two lightening sessions."
  },
  {
    beforeHairColor: "Level 6 light brown, natural",
    beforeHairType: "2B wavy, medium porosity",
    beforeCondition: "Virgin hair",
    beforeLevel: "6",
    afterHairColor: "Level 6 root blending to level 8 peachy-pink ends",
    afterLevel: "8",
    technique: "Peach color melt",
    formulaDetails: "Balayage lower 2/3 with Wella Blondor + 20 vol (1:2). Process 35 min. Tone: mix Pulp Riot Cupid + Blush + Clear (1:1:4) on lightened sections. Process 25 min under plastic. Leave root area natural.",
    colorBrand: "Pulp Riot / Wella",
    colorLine: "Semi-permanent / Blondor",
    colorShades: ["Cupid", "Blush", "Clear"],
    developer: "20 vol for lightener",
    lightener: "Wella Blondor",
    toner: "Pulp Riot Cupid + Blush diluted",
    additives: ["Olaplex No.1"],
    processingTime: "35 min lightener, 25 min color",
    tags: ["peach", "pink", "color-melt", "fashion-color", "pastel"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "3-3.5 hours",
    notes: "Heavy dilution with clear keeps it pastel and wearable. This will fade beautifully over 4-6 weeks to a soft blonde. Cool water rinse only."
  },
  // ─── FASHION / VIVID COLORS (81-90) ────────────────────
  {
    beforeHairColor: "Level 10 pre-lightened pale blonde",
    beforeHairType: "1A straight, high porosity",
    beforeCondition: "Pre-lightened, porous",
    beforeLevel: "10",
    afterHairColor: "Deep sapphire blue",
    afterLevel: "10",
    technique: "Vivid blue application",
    formulaDetails: "Pre-treat with Olaplex No.1. Apply Pulp Riot Nightfall (deep blue) root to ends. For dimension, mix Pulp Riot Mercury (silver) + Nightfall (1:3) on a few face-frame pieces. Process 30 min under plastic cap at room temp.",
    colorBrand: "Pulp Riot",
    colorLine: "Semi-Permanent",
    colorShades: ["Nightfall", "Mercury"],
    additives: ["Olaplex No.1", "Olaplex No.2"],
    processingTime: "30 min under plastic",
    tags: ["vivid", "blue", "fashion-color", "semi-permanent", "bold"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "2-2.5 hours",
    notes: "Must be pre-lightened to level 9-10. Blue is the longest-lasting vivid color. Warn client it may stain pillowcases initially. Cool water only."
  },
  {
    beforeHairColor: "Level 10 pre-lightened pale blonde",
    beforeHairType: "2A wavy, high porosity",
    beforeCondition: "Pre-lightened, needs bonding treatment",
    beforeLevel: "10",
    afterHairColor: "Vivid emerald green",
    afterLevel: "10",
    technique: "Vivid green application",
    formulaDetails: "Olaplex No.1 pre-treatment. Apply Pulp Riot Absinthe (green) + Area 51 (teal) (3:1) root to ends. Process 35 min under plastic. The touch of teal prevents it from fading to yellow-green.",
    colorBrand: "Pulp Riot",
    colorLine: "Semi-Permanent",
    colorShades: ["Absinthe", "Area 51"],
    additives: ["Olaplex No.1"],
    processingTime: "35 min under plastic",
    tags: ["vivid", "green", "emerald", "fashion-color", "bold"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "2-2.5 hours",
    notes: "Green fades to yellow-green, so adding teal extends the life. Must be level 10. Green is notoriously hard to remove later - make sure client understands the commitment."
  },
  {
    beforeHairColor: "Level 10 pre-lightened",
    beforeHairType: "1B straight, high porosity",
    beforeCondition: "Pre-lightened",
    beforeLevel: "10",
    afterHairColor: "Multi-tone rainbow: red, orange, yellow, green, blue, purple sections",
    afterLevel: "10",
    technique: "Rainbow color block",
    formulaDetails: "Section hair into 6 horizontal panels. Apply from bottom up: Pulp Riot Lava (red), Firefly (orange), Lemon (yellow), Absinthe (green), Nightfall (blue), Velvet (purple). Separate each section with foils. Process all simultaneously 30 min.",
    colorBrand: "Pulp Riot",
    colorLine: "Semi-Permanent",
    colorShades: ["Lava", "Firefly", "Lemon", "Absinthe", "Nightfall", "Velvet"],
    additives: ["Olaplex No.1"],
    processingTime: "30 min all sections simultaneously",
    tags: ["rainbow", "vivid", "color-block", "fashion-color", "creative"],
    difficulty: "advanced",
    priceRange: "$$$$",
    estimatedTime: "4-5 hours",
    notes: "Precise sectioning and foil placement is critical to prevent bleeding. Each color must be saturated fully. Rinse each section separately with cool water."
  },
  {
    beforeHairColor: "Level 10 pre-lightened with yellow patches",
    beforeHairType: "2A wavy, high porosity",
    beforeCondition: "Unevenly lightened, needs evening out",
    beforeLevel: "10",
    afterHairColor: "Deep violet-purple all-over",
    afterLevel: "10",
    technique: "Vivid purple application",
    formulaDetails: "Mix Pulp Riot Velvet + Jam (1:1) for deep purple. Apply evenly root to ends. For yellow patches, apply straight Velvet (more concentrated) first, process 10 min, then apply mixed formula over everything. Process 30 min.",
    colorBrand: "Pulp Riot",
    colorLine: "Semi-Permanent",
    colorShades: ["Velvet", "Jam"],
    additives: ["Olaplex No.1"],
    processingTime: "10 min spot + 30 min all-over",
    tags: ["vivid", "purple", "violet", "fashion-color", "even-coverage"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "2-3 hours",
    notes: "Purple covers uneven blonde well. Pre-apply concentrated color to yellow patches for even result. Purple fades to pink/lavender - a nice evolution."
  },
  {
    beforeHairColor: "Level 10 pre-lightened blonde",
    beforeHairType: "1B straight, high porosity",
    beforeCondition: "Pre-lightened, good condition",
    beforeLevel: "10",
    afterHairColor: "Soft lavender pastel all-over",
    afterLevel: "10",
    technique: "Pastel color application",
    formulaDetails: "Mix Pulp Riot Lilac + Clear (1:5) for ultra-pastel lavender. Apply evenly root to ends. Process 20 min at room temp - check every 5 min as pastels develop quickly on porous hair.",
    colorBrand: "Pulp Riot",
    colorLine: "Semi-Permanent",
    colorShades: ["Lilac", "Clear"],
    processingTime: "20 min, check every 5",
    tags: ["pastel", "lavender", "fashion-color", "soft", "trendy"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "1.5-2 hours",
    notes: "Pastels require VERY light base - level 10 minimum. Heavy dilution is key. This will last 2-4 weeks maximum. Perfect for clients wanting to try color temporarily."
  },
  {
    beforeHairColor: "Level 10 pre-lightened",
    beforeHairType: "2B wavy, high porosity",
    beforeCondition: "Pre-lightened",
    beforeLevel: "10",
    afterHairColor: "Shadow root dark to neon orange/coral ends",
    afterLevel: "10",
    technique: "Vivid shadow root color melt",
    formulaDetails: "Root: Pulp Riot Lava + Mercury (2:1) for muted red root. Mid: Pulp Riot Firefly (orange). Ends: Pulp Riot Cupid + Firefly (1:1) for coral. Apply in sections, blend between zones with a brush. Foil and process 30 min.",
    colorBrand: "Pulp Riot",
    colorLine: "Semi-Permanent",
    colorShades: ["Lava", "Mercury", "Firefly", "Cupid"],
    additives: ["Olaplex No.1"],
    processingTime: "30 min",
    tags: ["vivid", "orange", "coral", "shadow-root", "color-melt", "neon"],
    difficulty: "advanced",
    priceRange: "$$$$",
    estimatedTime: "3-4 hours",
    notes: "The muted root makes this more wearable than all-over neon. Blend zones carefully for seamless melt. Coral/orange fades faster than cool tones."
  },
  {
    beforeHairColor: "Level 7 dark blonde, previously had vivid color",
    beforeHairType: "1A straight, high porosity",
    beforeCondition: "Faded fashion color, stained green/blue undertone",
    beforeLevel: "7",
    afterHairColor: "Level 8 clean warm blonde, no fashion color residue",
    afterLevel: "8",
    technique: "Fashion color removal and correction",
    formulaDetails: "Step 1: Malibu C DDL treatment, process 20 min with heat. Rinse. Step 2: Apply Pravana Artificial Hair Color Extractor parts A+B, process 20 min. Rinse. Step 3: Light foils with Wella Blondor + 10 vol on remaining stained sections only. Process 20 min. Step 4: Tone Shades EQ 8WG + 8GI (1:1). Process 15 min.",
    colorBrand: "Pravana / Wella / Redken",
    colorLine: "Multiple",
    colorShades: ["8WG", "8GI"],
    developer: "10 vol for spot lightening",
    lightener: "Wella Blondor",
    toner: "Shades EQ 8WG + 8GI",
    additives: ["Malibu C DDL", "Olaplex No.1"],
    processingTime: "20 min DDL, 20 min extractor, 20 min foils, 15 min toner",
    tags: ["fashion-color-removal", "color-correction", "stain-removal", "multi-step"],
    difficulty: "advanced",
    priceRange: "$$$$",
    estimatedTime: "4-5 hours",
    notes: "Fashion color removal is a multi-step process. Never bleach first - it can lock in stain. Chemical removers first, then spot treat remaining stains."
  },
  {
    beforeHairColor: "Level 10 pre-lightened",
    beforeHairType: "2A wavy, high porosity",
    beforeCondition: "Pre-lightened",
    beforeLevel: "10",
    afterHairColor: "Cotton candy pink all-over",
    afterLevel: "10",
    technique: "Vivid pink application",
    formulaDetails: "Olaplex No.1 pre-treatment. Mix Pulp Riot Blush + Clear (1:2) for vibrant (not pastel) pink. Apply root to ends, saturate fully. Process 30 min under plastic cap. Rinse with cool water until runs clear.",
    colorBrand: "Pulp Riot",
    colorLine: "Semi-Permanent",
    colorShades: ["Blush", "Clear"],
    additives: ["Olaplex No.1"],
    processingTime: "30 min under plastic",
    tags: ["vivid", "pink", "cotton-candy", "fashion-color", "fun"],
    difficulty: "beginner",
    priceRange: "$$",
    estimatedTime: "1.5-2 hours",
    notes: "Pink is the most popular vivid color. The 1:2 dilution gives cotton candy vibrancy without being too intense. Fades to light blush pink beautifully."
  },
  {
    beforeHairColor: "Level 10 pre-lightened",
    beforeHairType: "1B straight, medium porosity",
    beforeCondition: "Pre-lightened evenly",
    beforeLevel: "10",
    afterHairColor: "Opal/holographic multi-tone pastels",
    afterLevel: "10",
    technique: "Opal hair technique",
    formulaDetails: "Mix 3 separate bowls: Bowl 1: Pulp Riot Lilac + Clear (1:6). Bowl 2: Pulp Riot Powder + Clear (1:6). Bowl 3: Pulp Riot Cupid + Clear (1:8). Apply in alternating panels - lavender, blue, pink - with some overlap for blending. Process 15 min only.",
    colorBrand: "Pulp Riot",
    colorLine: "Semi-Permanent",
    colorShades: ["Lilac", "Powder", "Cupid", "Clear"],
    processingTime: "15 min max",
    tags: ["opal", "holographic", "pastel", "multi-tone", "fashion-color", "creative"],
    difficulty: "advanced",
    priceRange: "$$$$",
    estimatedTime: "3-4 hours",
    notes: "Opal hair requires perfect level 10 base. Very heavy dilution creates the ethereal effect. Short processing time is critical - do not over-process."
  },
  {
    beforeHairColor: "Level 10 pre-lightened",
    beforeHairType: "2C curly, high porosity",
    beforeCondition: "Pre-lightened, curly texture",
    beforeLevel: "10",
    afterHairColor: "Sunset color melt: magenta roots to orange to yellow ends",
    afterLevel: "10",
    technique: "Vivid sunset color melt on curls",
    formulaDetails: "Work in sections following natural curl pattern. Root zone: Pulp Riot Jam (magenta). Mid zone: Pulp Riot Lava + Firefly (1:1) for red-orange. End zone: Pulp Riot Firefly + Lemon (1:1) for golden. Blend between zones. Process 30 min.",
    colorBrand: "Pulp Riot",
    colorLine: "Semi-Permanent",
    colorShades: ["Jam", "Lava", "Firefly", "Lemon"],
    additives: ["Olaplex No.1"],
    processingTime: "30 min",
    tags: ["vivid", "sunset", "color-melt", "curly", "multi-tone", "creative"],
    difficulty: "advanced",
    priceRange: "$$$$",
    estimatedTime: "4-5 hours",
    notes: "Curly sunset hair is stunning. Each curl catches different tones. Work with the natural curl clumps for most natural blending."
  },
  // ─── SPECIALTY / UNIQUE TECHNIQUES (91-100) ─────────────
  {
    beforeHairColor: "Level 5 medium brown, natural",
    beforeHairType: "1B straight, medium porosity",
    beforeCondition: "Virgin hair, wants dramatic change",
    beforeLevel: "5",
    afterHairColor: "Level 5 dark root with level 10 bright platinum panels (skunk stripe)",
    afterLevel: "10",
    technique: "Chunky face-frame panels (skunk stripe trend)",
    formulaDetails: "Section out 2-inch panels at each temple. Double foil underneath. Apply Schwarzkopf IGORA Vario Blond + 30 vol (1:2). Process 45 min, must reach pale yellow. Tone panels: BlondMe T-Ice. Process 10 min. Leave remaining hair untouched.",
    colorBrand: "Schwarzkopf",
    colorLine: "IGORA / BlondMe",
    colorShades: ["T-Ice"],
    developer: "30 vol",
    developerRatio: "1:2",
    lightener: "IGORA Vario Blond",
    toner: "BlondMe T-Ice",
    additives: ["IGORA Fibrebond"],
    processingTime: "45 min lightener, 10 min toner",
    tags: ["skunk-stripe", "chunky", "contrast", "platinum", "trendy", "bold"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "2.5-3 hours",
    notes: "The high contrast is intentional for this trend. Double foil prevents bleeding onto dark hair. Quick service with maximum impact."
  },
  {
    beforeHairColor: "Level 6 light brown, fine hair",
    beforeHairType: "1A straight, fine, medium porosity",
    beforeCondition: "Fine hair, wants volume appearance",
    beforeLevel: "6",
    afterHairColor: "Level 6 base with level 8 micro-highlights for fullness illusion",
    afterLevel: "8",
    technique: "Micro-weave highlights for volume illusion",
    formulaDetails: "Ultra-fine weaves (baby fine) throughout head. Closer together at crown for volume illusion. Redken Flash Lift + 20 vol (1:2). Process 30 min. Tone: Shades EQ 8N + 8GI (1:1). Process 15 min.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["8N", "8GI"],
    developer: "20 vol",
    developerRatio: "1:2",
    lightener: "Flash Lift",
    toner: "Shades EQ 8N + 8GI",
    processingTime: "30 min lightener, 15 min toner",
    tags: ["micro-highlights", "fine-hair", "volume-illusion", "subtle", "natural"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "3-4 hours",
    notes: "Ultra-fine highlights create the illusion of thicker, fuller hair. Concentrate more foils at the crown. The multi-tonal effect mimics natural depth."
  },
  {
    beforeHairColor: "Level 7 dark blonde with 3 inch dark regrowth",
    beforeHairType: "2A wavy, medium porosity",
    beforeCondition: "Growing out highlights, wants to transition gracefully",
    beforeLevel: "7",
    afterHairColor: "Grown-out root melting seamlessly into existing blonde",
    afterLevel: "8",
    technique: "Grow-out blend / transition service",
    formulaDetails: "Apply Redken Shades EQ 6N + 6NB (1:1) to root area, feather down 3 inches past demarcation line with a balayage motion. Process 20 min. This darkens the blonde near the root to match regrowth, creating seamless blend.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["6N", "6NB"],
    developer: "Processing solution",
    processingTime: "20 min",
    tags: ["grow-out", "transition", "root-blend", "low-maintenance", "natural"],
    difficulty: "beginner",
    priceRange: "$",
    estimatedTime: "45 min - 1 hour",
    notes: "Perfect for clients wanting to grow out gracefully without harsh lines. Extends time between appointments by 4-6 weeks."
  },
  {
    beforeHairColor: "Level 6 medium brown",
    beforeHairType: "2B wavy, medium porosity",
    beforeCondition: "Healthy, wants subtle change",
    beforeLevel: "6",
    afterHairColor: "Level 6 base with level 7 sun-kissed face frame only",
    afterLevel: "7",
    technique: "Natural sun-kissed face frame",
    formulaDetails: "Take thin babylight sections around face only (within 1 inch of hairline). Redken Flash Lift + 20 vol (1:2). Process 25 min. Tone: Shades EQ 7GB + Clear (1:1). Process 10 min. Rest of hair untouched.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["7GB", "Clear"],
    developer: "20 vol",
    developerRatio: "1:2",
    lightener: "Flash Lift",
    toner: "Shades EQ 7GB + Clear",
    processingTime: "25 min lightener, 10 min toner",
    tags: ["sun-kissed", "face-frame", "babylights", "subtle", "natural", "quick-service"],
    difficulty: "beginner",
    priceRange: "$",
    estimatedTime: "1-1.5 hours",
    notes: "Only 1 level of lift for the most natural sun-kissed effect. Perfect gateway service for color-shy clients."
  },
  {
    beforeHairColor: "Level 4 dark brown, coarse",
    beforeHairType: "3B curly, low porosity",
    beforeCondition: "Virgin, thick, coarse curls",
    beforeLevel: "4",
    afterHairColor: "Level 4 base with level 6 warm toffee balayage on curls",
    afterLevel: "6",
    technique: "Curly balayage with open-air processing",
    formulaDetails: "Apply lightener to stretched (not pulled tight) curls. Redken Flash Lift + 30 vol (1:1.5). Paint outside of curl springs for maximum visibility when curls bounce back. Process 40 min open air. Tone: Shades EQ 6WG + 6G (1:1). Process 20 min on lightened sections only.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["6WG", "6G"],
    developer: "30 vol",
    developerRatio: "1:1.5",
    lightener: "Flash Lift",
    toner: "Shades EQ 6WG + 6G",
    additives: ["Olaplex No.1"],
    processingTime: "40 min lightener, 20 min toner",
    tags: ["curly-balayage", "toffee", "curly-hair", "open-air", "warm-tone"],
    difficulty: "advanced",
    priceRange: "$$$",
    estimatedTime: "3.5-4 hours",
    notes: "Paint on stretched curls - they shrink 40-60% when dry. What looks subtle stretched will be perfect when curled. Focus on the curl surface that faces outward."
  },
  {
    beforeHairColor: "Level 8 blonde, even tone",
    beforeHairType: "1B straight, medium porosity",
    beforeCondition: "Previously colored, wants trendy look",
    beforeLevel: "8",
    afterHairColor: "Level 8 blonde with level 5 underlayer (peekaboo)",
    afterLevel: "5",
    technique: "Peekaboo color (hidden underlayer)",
    formulaDetails: "Section top 2/3 of hair up and clip. Apply Redken Shades EQ 5VRo + 5V (1:1) with processing solution to bottom 1/3 (nape area). Process 20 min. Top layer remains untouched blonde. When hair is down, the dark is hidden; when tucked behind ears or in updo, it reveals.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["5VRo", "5V"],
    developer: "Processing solution",
    processingTime: "20 min",
    tags: ["peekaboo", "hidden-color", "underlayer", "trendy", "creative", "work-appropriate"],
    difficulty: "beginner",
    priceRange: "$$",
    estimatedTime: "1-1.5 hours",
    notes: "Great for clients in professional settings who want fun color they can hide. Demi-permanent fades in 6-8 weeks if they change their mind."
  },
  {
    beforeHairColor: "Level 3 dark brown",
    beforeHairType: "1C straight, coarse, low porosity",
    beforeCondition: "Virgin, wants dramatic change",
    beforeLevel: "3",
    afterHairColor: "Level 3 dark base with hidden vivid purple underlayer",
    afterLevel: "3",
    technique: "Hidden vivid underlayer on dark hair",
    formulaDetails: "Section nape area (bottom 2 inches). Lighten with Schwarzkopf BlondMe + 30 vol (1:1.5). Process 40 min with heat. Must reach level 8 minimum. Tone: Apply Pulp Riot Velvet straight on lightened section. Process 30 min. Leave top layers untouched.",
    colorBrand: "Schwarzkopf / Pulp Riot",
    colorLine: "BlondMe / Semi-Permanent",
    colorShades: ["Velvet"],
    developer: "30 vol",
    lightener: "BlondMe",
    additives: ["BlondMe Bond Enforcing"],
    processingTime: "40 min lightener, 30 min vivid color",
    tags: ["hidden-vivid", "purple", "underlayer", "creative", "peekaboo", "dark-hair"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "3-3.5 hours",
    notes: "Only the bottom section is lightened - minimal damage to overall hair. When client wears hair down, it looks like natural dark brown. Ponytails and updos reveal the purple."
  },
  {
    beforeHairColor: "Level 6 light brown, post-pregnancy hair changes",
    beforeHairType: "2A wavy, high porosity",
    beforeCondition: "Post-pregnancy texture change, increased porosity, some hair loss",
    beforeLevel: "6",
    afterHairColor: "Level 7 warm golden brown with gentle dimension",
    afterLevel: "7",
    technique: "Gentle post-pregnancy color refresh",
    formulaDetails: "Use only demi-permanent for sensitivity. Apply Redken Shades EQ 7G + 7GB + Clear (1:1:1) with processing solution. Process 15 min max. The clear dilutes for gentler deposit. Follow with Olaplex No.2 treatment.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["7G", "7GB", "Clear"],
    developer: "Processing solution",
    additives: ["Olaplex No.2"],
    processingTime: "15 min",
    tags: ["post-pregnancy", "gentle", "demi-permanent", "sensitive-scalp", "warm-brown"],
    difficulty: "beginner",
    priceRange: "$",
    estimatedTime: "45 min - 1 hour",
    notes: "Post-pregnancy hair and scalp are more sensitive. Demi-permanent only, no ammonia. Patch test mandatory. Hormonal changes affect porosity and texture."
  },
  {
    beforeHairColor: "Level 5 medium brown",
    beforeHairType: "1B straight, medium porosity",
    beforeCondition: "Healthy, wants hair to look thicker",
    beforeLevel: "5",
    afterHairColor: "Level 5 base with level 4 lowlights and level 7 babylight highlights",
    afterLevel: "7",
    technique: "Dimension weave (lowlights + highlights together)",
    formulaDetails: "Alternate lowlight and highlight foils throughout. Lowlights: Wella Koleston 4/07 with 10 vol. Highlights: Redken Flash Lift + 20 vol. Process 30 min together. Tone highlighted sections: Shades EQ 7NB + 7V (3:1). Process 15 min.",
    colorBrand: "Redken / Wella",
    colorLine: "Shades EQ / Koleston",
    colorShades: ["4/07", "7NB", "7V"],
    developer: "10 vol lowlights, 20 vol highlights",
    lightener: "Flash Lift",
    toner: "Shades EQ 7NB + 7V on highlights",
    processingTime: "30 min foils, 15 min toner",
    tags: ["dimension-weave", "lowlights", "highlights", "fullness", "multi-tone"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "3-4 hours",
    notes: "Lowlights add depth, highlights add brightness - together they create incredible dimension. The contrast makes hair appear thicker. Touch of violet prevents brassiness."
  },
  {
    beforeHairColor: "Level 7 grown-out balayage, banding at mid-shaft",
    beforeHairType: "2A wavy, mixed porosity",
    beforeCondition: "Previous balayage grown out 6+ months, needs refresh",
    beforeLevel: "7",
    afterHairColor: "Level 8 refreshed seamless balayage with no banding",
    afterLevel: "8",
    technique: "Balayage refresh / maintenance",
    formulaDetails: "Add new balayage pieces at the root area only - do NOT re-lighten previously lightened ends. Redken Flash Lift + 20 vol (1:2) on new growth areas. Process 30 min. Tone all: Shades EQ 8V + 8GI + Clear (1:1:1). Process 20 min. The toner blends everything.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["8V", "8GI", "Clear"],
    developer: "20 vol",
    developerRatio: "1:2",
    lightener: "Flash Lift",
    toner: "Shades EQ 8V + 8GI + Clear",
    additives: ["Olaplex No.1"],
    processingTime: "30 min lightener, 20 min toner",
    tags: ["balayage-refresh", "maintenance", "seamless", "low-maintenance", "natural"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "2.5-3 hours",
    notes: "Never re-bleach already lightened ends - it causes breakage. Only add lightener where new dark growth is. The toner ties everything together."
  },
];

async function seedFormulas() {
  console.log(`Seeding ${formulas.length} formulas to ${API_URL}...`);

  let success = 0;
  let failed = 0;

  for (let i = 0; i < formulas.length; i++) {
    try {
      const res = await fetch(`${API_URL}/api/formulas`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-admin-secret': ADMIN_SECRET,
        },
        body: JSON.stringify(formulas[i]),
      });

      if (res.ok) {
        success++;
        process.stdout.write(`\r  Seeded ${success}/${formulas.length}`);
      } else {
        const err = await res.json();
        failed++;
        console.error(`\n  Failed #${i + 11}: ${err.error}`);
      }
    } catch (err: any) {
      failed++;
      console.error(`\n  Error #${i + 11}: ${err.message}`);
    }

    // Small delay to avoid rate limiting
    await new Promise(r => setTimeout(r, 200));
  }

  console.log(`\n\nDone! ${success} succeeded, ${failed} failed.`);
  console.log(`Total formulas in database: ${success + 10} (10 original + ${success} new)`);
}

seedFormulas();
