const API_URL = 'https://project-aiub5.vercel.app';
const ADMIN_SECRET = 'colorlab-admin-2026';

const formulas = [
  // ─── MORE GREY COVERAGE WITH 10 VOL RULE (72-80) ───────
  {
    beforeHairColor: "Level 7 dark blonde with 35% grey at crown",
    beforeHairType: "1B straight, fine",
    beforeCondition: "Grey concentrated at crown and part line",
    beforeLevel: "7",
    afterHairColor: "Level 7 natural blonde with grey blended",
    afterLevel: "7",
    technique: "Demi-permanent grey blending at crown",
    formulaDetails: "Apply Redken Shades EQ 7N + 7NB (1:1) with processing solution to crown and part line only. Process 20 min. Leave rest untouched. The demi blends grey 50% for natural look.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["7N", "7NB"],
    developer: "Processing solution",
    processingTime: "20 min",
    tags: ["grey-blending", "crown", "spot-treatment", "natural", "low-commitment"],
    difficulty: "beginner",
    priceRange: "$",
    estimatedTime: "30-45 min",
    notes: "Quick targeted service. No need to color the whole head when grey is concentrated in one area."
  },
  {
    beforeHairColor: "Level 5 medium brown with 55% grey throughout",
    beforeHairType: "2A wavy, medium porosity",
    beforeCondition: "Regular grey coverage client, sensitive scalp",
    beforeLevel: "5",
    afterHairColor: "Level 5 warm brown with 100% grey coverage",
    afterLevel: "5",
    technique: "Gentle grey coverage for sensitive scalp",
    formulaDetails: "Use ammonia-free Wella Color Touch 5/03 + 5/0 (1:1) with 4% emulsion (equivalent to 13 vol). Apply to new growth. Process 30 min under plastic cap. Pull through ends for last 5 min.",
    colorBrand: "Wella",
    colorLine: "Color Touch",
    colorShades: ["5/03", "5/0"],
    developer: "4% emulsion",
    developerRatio: "1:1",
    processingTime: "30 min root, 5 min ends",
    tags: ["grey-coverage", "sensitive-scalp", "ammonia-free", "gentle", "wella"],
    difficulty: "beginner",
    priceRange: "$$",
    estimatedTime: "1.5 hours",
    notes: "Color Touch is ammonia-free - ideal for sensitive scalps. Covers up to 70% grey. For higher grey percentage, add 5/0 (pure base)."
  },
  {
    beforeHairColor: "Level 4 dark brown with 100% grey (fully white)",
    beforeHairType: "1C straight, coarse, very resistant",
    beforeCondition: "Fully white/grey, wiry texture, very resistant",
    beforeLevel: "4",
    afterHairColor: "Level 4 dark brown with total grey coverage",
    afterLevel: "4",
    technique: "Maximum strength grey coverage protocol",
    formulaDetails: "Pre-soften entire head with 10 vol, process 20 min, blot. Mix Wella Koleston Perfect 4/0 + 4/07 + 3/0 (2:1:0.5) with 10 vol (1:1). Apply to most resistant areas first (temples, hairline). Process 45 min full timing.",
    colorBrand: "Wella",
    colorLine: "Koleston Perfect",
    colorShades: ["4/0", "4/07", "3/0"],
    developer: "10 vol",
    developerRatio: "1:1",
    processingTime: "20 min pre-soften, 45 min color",
    tags: ["grey-coverage", "100-percent-grey", "resistant", "maximum-coverage", "wella"],
    difficulty: "intermediate",
    priceRange: "$$",
    estimatedTime: "2-2.5 hours",
    notes: "100% grey is the most resistant. Extended pre-soften time opens cuticle. The half-part of 3/0 deepens and anchors. Full 45 min processing is mandatory. Use 10 vol for deposit."
  },
  {
    beforeHairColor: "Level 8 light blonde with 20% grey emerging",
    beforeHairType: "1A straight, fine",
    beforeCondition: "Early grey, mostly around face",
    beforeLevel: "8",
    afterHairColor: "Level 9 bright blonde highlights camouflaging grey",
    afterLevel: "9",
    technique: "Highlight-based grey camouflage",
    formulaDetails: "Fine babylight foils concentrated around face and part. Wella Blondor + 20 vol (1:2). Process 25 min. Tone: Shades EQ 9V + Clear (1:2). Process 10 min. Grey hairs become indistinguishable from highlights.",
    colorBrand: "Wella / Redken",
    colorLine: "Blondor / Shades EQ",
    colorShades: ["9V", "Clear"],
    developer: "20 vol",
    lightener: "Wella Blondor",
    toner: "Shades EQ 9V + Clear",
    processingTime: "25 min lightener, 10 min toner",
    tags: ["grey-camouflage", "highlights", "blonde", "babylights", "face-frame"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "2-2.5 hours",
    notes: "Best grey camouflage technique for blondes. The highlights make grey invisible. Zero harsh line of demarcation as it grows."
  },
  // ─── MORE BALAYAGE/HIGHLIGHT VARIATIONS (81-90) ─────────
  {
    beforeHairColor: "Level 3 dark brown, Asian hair",
    beforeHairType: "1C straight, coarse, low porosity",
    beforeCondition: "Virgin, resistant Asian hair",
    beforeLevel: "3",
    afterHairColor: "Level 3 base with level 5 soft ash brown balayage",
    afterLevel: "5",
    technique: "Subtle Asian hair balayage",
    formulaDetails: "Use Schwarzkopf BlondMe + 30 vol (1:1) with heat. Paint balayage on lower 1/3 only. Wrap in foils. Process 40 min with heat cap. Tone: BlondMe T-Ice + T-Sand (1:2). Process 10 min.",
    colorBrand: "Schwarzkopf",
    colorLine: "BlondMe",
    colorShades: ["T-Ice", "T-Sand"],
    developer: "30 vol",
    lightener: "BlondMe",
    toner: "BlondMe T-Ice + T-Sand",
    additives: ["BlondMe Bond Enforcing"],
    processingTime: "40 min with heat, 10 min toner",
    tags: ["asian-hair", "subtle-balayage", "low-porosity", "resistant", "natural"],
    difficulty: "advanced",
    priceRange: "$$$",
    estimatedTime: "3.5-4 hours",
    notes: "Asian hair is resistant - needs heat and higher vol. Don't expect dramatic lift in one session. Subtle is beautiful. 2 sessions recommended for more lift."
  },
  {
    beforeHairColor: "Level 6 light brown with old grown-out highlights",
    beforeHairType: "2A wavy, medium-high porosity",
    beforeCondition: "Old highlights at ends, band at mid-shaft",
    beforeLevel: "6",
    afterHairColor: "Level 8 seamless bright blonde with lived-in root",
    afterLevel: "8",
    technique: "Full balayage with baby lights at hairline",
    formulaDetails: "Babylights at face frame with foils. Open-air balayage through crown and sides. Foilyage on back sections. Redken Flash Lift + 30 vol (1:2) for all. Process 40 min. Tone: Shades EQ 9P + 9N + Clear (1:1:1). Process 20 min.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["9P", "9N", "Clear"],
    developer: "30 vol",
    developerRatio: "1:2",
    lightener: "Flash Lift",
    toner: "Shades EQ 9P + 9N + Clear",
    additives: ["Olaplex No.1"],
    processingTime: "40 min lightener, 20 min toner",
    tags: ["full-balayage", "babylights", "bright-blonde", "lived-in", "seamless"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "3.5-4 hours",
    notes: "Use multiple techniques in one session for maximum dimension. Babylights at face give brightness where it matters most."
  },
  {
    beforeHairColor: "Level 2 near-black, natural",
    beforeHairType: "4A coily, high porosity",
    beforeCondition: "Natural coily hair, some dryness",
    beforeLevel: "2",
    afterHairColor: "Level 2 base with level 4 warm brown highlights on coils",
    afterLevel: "4",
    technique: "Coil-painting highlights",
    formulaDetails: "Stretch coils gently (do NOT pull tight) and paint highlights on outer surface. Redken Flash Lift + 20 vol (1:1). Process 30 min open air. Tone: Shades EQ 4WG with processing solution. Process 15 min on lightened coils only.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["4WG"],
    developer: "20 vol",
    lightener: "Flash Lift",
    toner: "Shades EQ 4WG",
    additives: ["Olaplex No.1"],
    processingTime: "30 min lightener, 15 min toner",
    tags: ["coily-hair", "natural-hair", "highlights", "warm-brown", "gentle"],
    difficulty: "advanced",
    priceRange: "$$$",
    estimatedTime: "3-4 hours",
    notes: "Coily hair is delicate - use lower volume developer and less processing time. The subtle warm highlights catch light beautifully on coils. Deep condition after."
  },
  {
    beforeHairColor: "Level 5 medium brown",
    beforeHairType: "2B wavy, medium porosity",
    beforeCondition: "Previously highlighted 8 months ago",
    beforeLevel: "5",
    afterHairColor: "Level 7 warm golden balayage with shadow root",
    afterLevel: "7",
    technique: "Balayage with intentional shadow root",
    formulaDetails: "Balayage with Redken Flash Lift + 30 vol (1:2). Leave 2 inch root area completely untouched. Process 35 min. Shadow root: Shades EQ 5NB at root, feather down 3 inches. Tone lengths: Shades EQ 7GB + 7G (2:1). Process everything 20 min together.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["5NB", "7GB", "7G"],
    developer: "30 vol lightener, processing solution toner",
    developerRatio: "1:2",
    lightener: "Flash Lift",
    toner: "Multi-zone Shades EQ",
    additives: ["Olaplex No.1"],
    processingTime: "35 min lightener, 20 min toner",
    tags: ["shadow-root", "golden-balayage", "warm-tone", "dimensional", "low-maintenance"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "3-3.5 hours",
    notes: "The intentional shadow root means this grows out beautifully. Client can go 12-16 weeks between appointments."
  },
  {
    beforeHairColor: "Level 7 dark blonde, flat color",
    beforeHairType: "1A straight, fine",
    beforeCondition: "Single-process color, flat appearance",
    beforeLevel: "7",
    afterHairColor: "Level 8 bright ribbon highlights with depth",
    afterLevel: "8",
    technique: "Ribbon highlights",
    formulaDetails: "Take wide (1 inch) ribbon-like sections and foil. Alternate with skipped sections for contrast. Redken Flash Lift + 20 vol (1:2). Process 30 min. Tone: Shades EQ 8GI + 8N (1:1). Process 15 min.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["8GI", "8N"],
    developer: "20 vol",
    developerRatio: "1:2",
    lightener: "Flash Lift",
    toner: "Shades EQ 8GI + 8N",
    processingTime: "30 min lightener, 15 min toner",
    tags: ["ribbon-highlights", "chunky", "contrast", "bold", "dimension"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "2.5-3 hours",
    notes: "Ribbon highlights create bolder contrast than babylights. The wide sections create a stripy but intentional look. Trendy chunky 90s-inspired style."
  },
  {
    beforeHairColor: "Level 4 dark brown with warm undertones",
    beforeHairType: "2A wavy, medium porosity",
    beforeCondition: "Virgin hair",
    beforeLevel: "4",
    afterHairColor: "Level 4 base with level 6 face-frame and level 8 ends",
    afterLevel: "8",
    technique: "Graduated balayage (darker at top, lighter at ends)",
    formulaDetails: "Paint balayage graduating from light touch at ear level to heavy saturation at ends. Redken Flash Lift + 30 vol (1:2). Face frame pieces get extra saturation. Process 40 min. Tone: Shades EQ 8V + 8GI (1:1) on ends, 6NB on mid sections. Process 20 min.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["8V", "8GI", "6NB"],
    developer: "30 vol",
    developerRatio: "1:2",
    lightener: "Flash Lift",
    toner: "Multi-zone Shades EQ",
    additives: ["Olaplex No.1"],
    processingTime: "40 min lightener, 20 min toner",
    tags: ["graduated-balayage", "natural-gradient", "face-frame", "dimensional"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "3-4 hours",
    notes: "The graduation creates the most natural-looking lightness. Heavier at ends mimics how the sun naturally lightens hair."
  },
  // ─── MORE SPECIALTY (91-100) ────────────────────────────
  {
    beforeHairColor: "Level 6 light brown, previously colored",
    beforeHairType: "2A wavy, medium porosity",
    beforeCondition: "Previously single-process, wants change",
    beforeLevel: "6",
    afterHairColor: "Level 6 rich mocha with copper face frame",
    afterLevel: "6",
    technique: "Copper money piece on brunette base",
    formulaDetails: "Face frame foils: Redken Flash Lift + 20 vol. Process 30 min to level 8. Tone face frame: Shades EQ 7C + 7RR (2:1). Process 15 min. Base refresh: Shades EQ 5NBr + 5N (1:1) all over remaining hair. Process 20 min.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["7C", "7RR", "5NBr", "5N"],
    developer: "20 vol foils, processing solution base",
    lightener: "Flash Lift",
    toner: "Multi-formula Shades EQ",
    processingTime: "30 min foils, 20 min base",
    tags: ["copper-money-piece", "brunette", "face-frame", "trendy", "two-tone"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "2.5-3 hours",
    notes: "Copper face framing on a brunette base is incredibly flattering. The warm copper brightens the face while the rich base adds depth."
  },
  {
    beforeHairColor: "Level 9 light blonde",
    beforeHairType: "1B straight, high porosity",
    beforeCondition: "Previously bleached",
    beforeLevel: "9",
    afterHairColor: "Level 9 chrome/metallic silver",
    afterLevel: "9",
    technique: "Chrome metallic finish",
    formulaDetails: "Must be even level 9-10 base. Apply Schwarzkopf BlondMe Toning T-Steel straight. Process 15 min. If too dark, reapply diluted with T-Ice + Clear (1:1:1). Process 5-10 min. The steel creates a true chrome metallic finish.",
    colorBrand: "Schwarzkopf",
    colorLine: "BlondMe",
    colorShades: ["T-Steel", "T-Ice", "Clear"],
    developer: "BlondMe Toning developer",
    processingTime: "15 min, or 5-10 min diluted second pass",
    tags: ["chrome", "metallic", "silver", "fashion-forward", "editorial"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "1-1.5 hours",
    notes: "Chrome/metallic finish is editorial and fashion-forward. Base must be perfectly even. The T-Steel creates that true mercury/chrome look."
  },
  {
    beforeHairColor: "Level 5 medium brown with 40% grey",
    beforeHairType: "2B wavy, medium porosity",
    beforeCondition: "Grey growing in, tired of full coverage",
    beforeLevel: "5",
    afterHairColor: "Level 6 soft grey-blended brown with lowlights",
    afterLevel: "6",
    technique: "Grey transition with lowlights",
    formulaDetails: "Lowlight foils with Wella Koleston 5/07 + 10 vol (1:1) through grey areas only to add back brown dimension. Leave grey sections between foils untouched. Gloss all over: Shades EQ 6N + Clear (1:2). Process 15 min.",
    colorBrand: "Wella / Redken",
    colorLine: "Koleston / Shades EQ",
    colorShades: ["5/07", "6N", "Clear"],
    developer: "10 vol lowlights, processing solution gloss",
    processingTime: "30 min lowlights, 15 min gloss",
    tags: ["grey-transition", "lowlights", "embracing-grey", "natural", "modern"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "2.5-3 hours",
    notes: "Lowlights through grey areas add back dimension without covering all the grey. The all-over gloss evens the tone. Great transition technique for clients going natural."
  },
  {
    beforeHairColor: "Level 7 medium blonde with brassy roots",
    beforeHairType: "1A straight, fine",
    beforeCondition: "Root regrowth with brassy tone",
    beforeLevel: "7",
    afterHairColor: "Level 9 bright cool blonde, roots blended",
    afterLevel: "9",
    technique: "Root touch-up with toner refresh",
    formulaDetails: "Roots: Wella Blondor + 20 vol (1:2) in foils at root area only. Process 25 min. Tone entire head: Shades EQ 9V + 9P + Clear (1:1:1). Process 15 min.",
    colorBrand: "Wella / Redken",
    colorLine: "Blondor / Shades EQ",
    colorShades: ["9V", "9P", "Clear"],
    developer: "20 vol root",
    developerRatio: "1:2",
    lightener: "Wella Blondor",
    toner: "Shades EQ 9V + 9P + Clear",
    processingTime: "25 min root foils, 15 min toner",
    tags: ["root-touch-up", "maintenance", "blonde", "cool-tone", "toner-refresh"],
    difficulty: "beginner",
    priceRange: "$$",
    estimatedTime: "1.5-2 hours",
    notes: "Standard blonde maintenance service. Root foils only - never re-bleach lengths. The all-over toner refreshes and neutralizes brassiness."
  },
  {
    beforeHairColor: "Level 6 light brown",
    beforeHairType: "2C curly, medium porosity",
    beforeCondition: "Natural curly, healthy",
    beforeLevel: "6",
    afterHairColor: "Level 6 rich auburn with copper babylights on curls",
    afterLevel: "6",
    technique: "Auburn base with copper curl highlights",
    formulaDetails: "First: paint copper on select curls using Pintura technique. Redken Flash Lift + 20 vol (1:1). Process 25 min. Tone copper curls: Shades EQ 7C + 7RR (1:1). Process 10 min. Base: Wella Koleston 6/45 with 10 vol on remaining hair. Process 30 min.",
    colorBrand: "Wella / Redken",
    colorLine: "Koleston / Shades EQ",
    colorShades: ["6/45", "7C", "7RR"],
    developer: "20 vol highlights, 10 vol base",
    lightener: "Flash Lift",
    toner: "Shades EQ 7C + 7RR",
    processingTime: "25 min highlights, 30 min base",
    tags: ["auburn", "copper-highlights", "curly-hair", "dimensional-red", "pintura"],
    difficulty: "advanced",
    priceRange: "$$$",
    estimatedTime: "3.5-4 hours",
    notes: "The copper highlighted curls catch light beautifully against the auburn base. Curly red hair is stunning. Color-safe products are essential."
  },
  {
    beforeHairColor: "Level 5 brown with permanent black box dye on ends",
    beforeHairType: "1B straight, low porosity on dyed ends",
    beforeCondition: "Box dye only on lower half, natural on top",
    beforeLevel: "5",
    afterHairColor: "Level 5 uniform medium brown, blended",
    afterLevel: "5",
    technique: "Blending box dye demarcation",
    formulaDetails: "Natural top half: Apply Shades EQ 5N with processing solution. Process 20 min. Box-dyed lower half: Apply Joico Color Eraser, process 20 min with heat. Rinse. Re-apply Shades EQ 5N + 5WG (2:1) on lower half. Process 20 min.",
    colorBrand: "Redken / Joico",
    colorLine: "Shades EQ",
    colorShades: ["5N", "5WG"],
    developer: "Processing solution",
    additives: ["Olaplex No.1"],
    processingTime: "20 min top, 20 min remover, 20 min re-color",
    tags: ["box-dye-fix", "blending", "color-correction", "demarcation", "even-tone"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "2.5-3 hours",
    notes: "Color remover on box-dyed sections only. Multiple sessions may be needed. Do not bleach box-dyed hair - use color remover first."
  },
  {
    beforeHairColor: "Level 10 bleached platinum",
    beforeHairType: "2A wavy, very high porosity",
    beforeCondition: "Over-processed, elastic, needs repair",
    beforeLevel: "10",
    afterHairColor: "Level 10 healthy-looking platinum with shine",
    afterLevel: "10",
    technique: "Repair treatment + shine gloss",
    formulaDetails: "Step 1: Olaplex No.1 treatment, 10 min. Step 2: K18 leave-in mask, 4 min. Step 3: Gloss with Shades EQ Clear + 9V (4:1) with processing solution. Process 10 min. Step 4: Olaplex No.2, process 20 min.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["Clear", "9V"],
    developer: "Processing solution",
    additives: ["Olaplex No.1", "Olaplex No.2", "K18"],
    processingTime: "10 min Olaplex, 4 min K18, 10 min gloss, 20 min No.2",
    tags: ["repair", "treatment", "shine", "platinum-maintenance", "bond-repair"],
    difficulty: "beginner",
    priceRange: "$$",
    estimatedTime: "1-1.5 hours",
    notes: "No color change - purely a repair and shine service. Essential for maintaining platinum hair health. The tiny bit of 9V in the gloss keeps it cool-toned."
  },
  {
    beforeHairColor: "Level 6 light brown, postpartum hair",
    beforeHairType: "1B straight, medium porosity",
    beforeCondition: "Post-pregnancy, new baby hairs at hairline, hormonal texture change",
    beforeLevel: "6",
    afterHairColor: "Level 7 sun-kissed light brown with face-frame brightness",
    afterLevel: "7",
    technique: "Gentle postpartum brightening service",
    formulaDetails: "Face frame babylights only with Redken Flash Lift + 20 vol (1:2). Take extra fine sections to avoid baby hairs at hairline. Process 25 min. Tone: Shades EQ 7GB + Clear (1:2). Process 10 min. Rest of hair: Shades EQ 6G with processing solution for gloss.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["7GB", "Clear", "6G"],
    developer: "20 vol face frame, processing solution gloss",
    lightener: "Flash Lift",
    toner: "Multi-zone Shades EQ",
    processingTime: "25 min foils, 10 min toner",
    tags: ["postpartum", "gentle", "face-frame", "babylights", "sensitive"],
    difficulty: "beginner",
    priceRange: "$$",
    estimatedTime: "1.5-2 hours",
    notes: "Postpartum clients need extra gentle services. Avoid touching the new baby hairs at hairline. Patch test mandatory - hormones change sensitivity."
  },
  {
    beforeHairColor: "Level 4 dark brown",
    beforeHairType: "3C coily, medium-high porosity",
    beforeCondition: "Natural 3C curls, some dryness",
    beforeLevel: "4",
    afterHairColor: "Level 4 base with golden-bronze highlights on coils",
    afterLevel: "6",
    technique: "Twist-and-paint highlighting for coily hair",
    formulaDetails: "Two-strand twist sections of hair. Paint lightener on the outside of each twist. Schwarzkopf BlondMe + 20 vol (1:1). Process 30 min open air. Untwist and tone: BlondMe T-Caramel + T-Sand (1:1). Process 10 min.",
    colorBrand: "Schwarzkopf",
    colorLine: "BlondMe",
    colorShades: ["T-Caramel", "T-Sand"],
    developer: "20 vol",
    lightener: "BlondMe",
    toner: "BlondMe T-Caramel + T-Sand",
    additives: ["BlondMe Bond Enforcing"],
    processingTime: "30 min lightener, 10 min toner",
    tags: ["coily-hair", "twist-paint", "golden-bronze", "natural-hair", "textured"],
    difficulty: "advanced",
    priceRange: "$$$",
    estimatedTime: "3.5-4 hours",
    notes: "The twist technique keeps lightener controlled on coily hair. When untwisted, the highlights appear on the high points of each coil. Beautiful dimensional result."
  },
  {
    beforeHairColor: "Level 7 dark blonde",
    beforeHairType: "1B straight, medium porosity",
    beforeCondition: "Healthy, wants editorial look",
    beforeLevel: "7",
    afterHairColor: "Level 7 base with bright platinum and dark chocolate contrast panels",
    afterLevel: "7",
    technique: "High-contrast color blocking",
    formulaDetails: "Section hair into 3 panels: center and two sides. Center panel: lighten with Wella Blondor + 30 vol to level 10. Process 40 min. Side panels: Wella Koleston 4/07 + 10 vol. Process 30 min. Tone center: BlondMe T-Ice. Process 10 min. Three distinct tones.",
    colorBrand: "Wella / Schwarzkopf",
    colorLine: "Blondor / Koleston / BlondMe",
    colorShades: ["4/07", "T-Ice"],
    developer: "30 vol center, 10 vol sides",
    lightener: "Wella Blondor",
    toner: "BlondMe T-Ice",
    additives: ["Olaplex No.1"],
    processingTime: "40 min center, 30 min sides, 10 min toner",
    tags: ["color-blocking", "editorial", "high-contrast", "creative", "bold"],
    difficulty: "advanced",
    priceRange: "$$$$",
    estimatedTime: "4-5 hours",
    notes: "Editorial color blocking is bold and artistic. Precise sectioning is critical. Foil barriers between sections prevent bleeding. Not for the faint of heart."
  },
  {
    beforeHairColor: "Level 5 medium brown, regular color client",
    beforeHairType: "2A wavy, medium porosity",
    beforeCondition: "Regular client, quarterly balayage maintenance",
    beforeLevel: "5",
    afterHairColor: "Level 7 refreshed warm balayage with toned ends",
    afterLevel: "7",
    technique: "Quarterly balayage maintenance + gloss",
    formulaDetails: "Touch up balayage at root area only where dark has grown in. Redken Flash Lift + 20 vol (1:2). Minimal foils - just filling in gaps. Process 25 min. All-over gloss: Shades EQ 7GB + 7NB + Clear (1:1:1). Process 20 min.",
    colorBrand: "Redken",
    colorLine: "Shades EQ",
    colorShades: ["7GB", "7NB", "Clear"],
    developer: "20 vol touch-up, processing solution gloss",
    lightener: "Flash Lift",
    toner: "Shades EQ 7GB + 7NB + Clear",
    processingTime: "25 min touch-up, 20 min gloss",
    tags: ["maintenance", "balayage-refresh", "quarterly", "gloss", "low-maintenance"],
    difficulty: "beginner",
    priceRange: "$$",
    estimatedTime: "2-2.5 hours",
    notes: "Maintenance visits should be quick and focused. Only lighten new dark growth. The all-over gloss refreshes tone and adds shine. Perfect recurring appointment."
  },
  {
    beforeHairColor: "Level 6 light brown with 65% grey",
    beforeHairType: "2A wavy, medium porosity",
    beforeCondition: "Heavy grey, wants to stop fighting it",
    beforeLevel: "6",
    afterHairColor: "Level 8 bright silver-blonde embracing grey",
    afterLevel: "8",
    technique: "Full transition to silver/grey embrace",
    formulaDetails: "Step 1: Full head fine foils with Wella Blondor + 20 vol (1:2). Lighten dark sections to match grey level. Process 35 min. Step 2: Tone all over with Wella Color Touch 9/16 + 8/81 (1:1) with 4% emulsion. Process 15 min. Creates unified silver-blonde.",
    colorBrand: "Wella",
    colorLine: "Blondor / Color Touch",
    colorShades: ["9/16", "8/81"],
    developer: "20 vol lightener, 4% emulsion toner",
    lightener: "Wella Blondor",
    toner: "Color Touch 9/16 + 8/81",
    additives: ["Olaplex No.1"],
    processingTime: "35 min lightener, 15 min toner",
    tags: ["grey-embrace", "silver", "transition", "liberating", "low-maintenance"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "3-4 hours",
    notes: "This service lightens the remaining dark hair to match the grey, creating a beautiful unified silver. The client never needs grey coverage again. Life-changing service."
  },
  {
    beforeHairColor: "Level 8 light blonde",
    beforeHairType: "1B straight, medium porosity",
    beforeCondition: "Healthy blonde, wants something fun but temporary",
    beforeLevel: "8",
    afterHairColor: "Level 8 blonde with temporary pastel pink dip-dye ends",
    afterLevel: "8",
    technique: "Temporary dip-dye with direct dye",
    formulaDetails: "No lightening needed on blonde base. Mix Pulp Riot Blush + Clear (1:4) for soft pastel pink. Apply to bottom 3-4 inches only. Wrap in plastic. Process 15 min. Cool water rinse. This will wash out in 4-8 washes.",
    colorBrand: "Pulp Riot",
    colorLine: "Semi-Permanent",
    colorShades: ["Blush", "Clear"],
    processingTime: "15 min",
    tags: ["temporary", "dip-dye", "pink", "fun", "commitment-free", "quick-service"],
    difficulty: "beginner",
    priceRange: "$",
    estimatedTime: "30-45 min",
    notes: "Perfect for clients wanting to try color without commitment. Will wash out in 4-8 shampoos. Great for events, festivals, or just for fun."
  },
  {
    beforeHairColor: "Level 5 medium brown with 50% grey",
    beforeHairType: "2A wavy, medium porosity",
    beforeCondition: "Grey at temples, through crown, scattered throughout",
    beforeLevel: "5",
    afterHairColor: "Level 5 rich brown with dimensional grey-blending highlights",
    afterLevel: "7",
    technique: "Grey-blending dimensional color (highlights + base)",
    formulaDetails: "Highlight foils through grey areas: Redken Flash Lift + 20 vol (1:2). Process 30 min. Base color on non-highlighted sections: Wella Koleston 5/07 + 5/03 (1:1) with 10 vol. Process 35 min. Tone highlights: Shades EQ 7NB + 7GI (1:1). Process 15 min.",
    colorBrand: "Wella / Redken",
    colorLine: "Koleston / Shades EQ",
    colorShades: ["5/07", "5/03", "7NB", "7GI"],
    developer: "20 vol highlights, 10 vol base",
    lightener: "Flash Lift",
    toner: "Shades EQ 7NB + 7GI",
    processingTime: "30 min foils, 35 min base, 15 min toner",
    tags: ["grey-blending", "dimensional", "highlights-base-combo", "natural", "multi-technique"],
    difficulty: "intermediate",
    priceRange: "$$$",
    estimatedTime: "3-3.5 hours",
    notes: "Combining highlights with grey-covering base gives the most natural result. Highlights break up the flatness of single-process grey coverage. Use 10 vol for base on grey areas."
  },
];

async function seedFormulas() {
  console.log(`Seeding ${formulas.length} formulas to ${API_URL}...`);
  let success = 0;
  let failed = 0;

  for (let i = 0; i < formulas.length; i++) {
    try {
      const res = await fetch(`${API_URL}/api/formulas`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-admin-secret': ADMIN_SECRET,
        },
        body: JSON.stringify(formulas[i]),
      });
      if (res.ok) {
        success++;
        process.stdout.write(`\r  Seeded ${success}/${formulas.length}`);
      } else {
        const err = await res.json();
        failed++;
        console.error(`\n  Failed #${i}: ${err.error}`);
      }
    } catch (err: any) {
      failed++;
      console.error(`\n  Error #${i}: ${err.message}`);
    }
    await new Promise(r => setTimeout(r, 200));
  }
  console.log(`\n\nDone! ${success} succeeded, ${failed} failed.`);
}

seedFormulas();
